//! 8-player booster-draft client flow against 7 bots.
//!
//! Bevy systems wired up at `AppState::Drafting`. Three sequential
//! sub-phases live behind a single `DraftSession` resource:
//!
//! 1. **Drafting** — current pack laid out as a 5×3 grid; the user
//!    clicks a card to pick it. All 7 bots auto-pick simultaneously
//!    via `crabomination::draft::bot_pick`. Packs pass left (rounds
//!    1 + 3) or right (round 2). After 3 packs × 15 picks, transitions
//!    to deckbuilding.
//!
//! 2. **Deckbuilding** — main / sideboard tabs of all 45 picks plus
//!    +/- buttons for each basic land color. Clicking a card moves it
//!    between main and sideboard. The "Confirm Deck" button activates
//!    once the main deck has at least 40 cards (drafted + basics).
//!
//! 3. **Opponent select** — the 7 bots' decks are shown by color
//!    identity ("P3 (UR)", "P4 (BG)", …). Clicking one writes the
//!    chosen player + opponent decks into the `DraftedDecks` resource
//!    and transitions to `AppState::InGame`. `start_net_session_from_menu`
//!    reads `DraftedDecks` instead of rerolling a fresh state.
//!
//! The whole flow is client-side — no server / wire protocol. The
//! draft picks happen in-process and the resulting decks are fed
//! directly into the existing in-process bot match infrastructure.

use std::collections::HashMap;

use bevy::prelude::*;

use crabomination::cube::CardFactory;
use crabomination::draft::{
    DraftPool, PACKS_PER_SEAT, PACK_SIZE, POD_SIZE, basic_land_factory, bot_pick,
    enforce_copy_cap, suggest_basic_split, suggest_main_deck, top_two_colors,
};
// Bevy's `Color` lives in the prelude (`use bevy::prelude::*` above).
// Import the engine's mana color under an alias to keep the two
// distinct everywhere in this file.
use crabomination::mana::Color as ManaColor;

use crate::menu::{AppState, DraftedDecks, MatchFormat, PendingDraftFormat};
use crate::scryfall;
use crate::theme::{self, UiFonts};

// ── Constants ────────────────────────────────────────────────────────────────

/// Magic card aspect ratio (printed-card 63mm × 88mm).
const CARD_ASPECT_H_OVER_W: f32 = 88.0 / 63.0;

/// Floor / ceiling for the dynamically-sized pack-card width. We never
/// shrink below this (gets unreadable) or grow past this (a single
/// remaining card shouldn't fill the whole screen). The dynamic sizing
/// in `compute_pack_card_width` snaps within this range.
const PACK_CARD_W_MIN: f32 = 130.0;
const PACK_CARD_W_MAX: f32 = 320.0;

const PICKS_TAB_CARD_W: f32 = 120.0;
const PICKS_TAB_CARD_H: f32 = PICKS_TAB_CARD_W * CARD_ASPECT_H_OVER_W;

/// Reserved vertical space above and below the pack grid: header bar
/// (~62px), stats footer (~100px), and a bit of breathing room. Used by
/// `compute_pack_card_width` to figure out how much vertical room the
/// grid actually has.
const PACK_GRID_CHROME_PX: f32 = 200.0;
/// Padding inside the grid container (`spawn_pack_grid` sets 20px all
/// around) plus a small slack to keep cards off the scrollbar.
const PACK_GRID_PADDING_PX: f32 = 60.0;
/// Per-card gutter — must match the `column_gap` / `row_gap` set on the
/// grid node in `spawn_pack_grid`.
const PACK_GRID_GAP_PX: f32 = 12.0;
const DECKBUILD_CARD_W: f32 = 90.0;
const DECKBUILD_CARD_H: f32 = DECKBUILD_CARD_W * (88.0 / 63.0);
/// Mouse-wheel scroll speed. One line ≈ this many pixels along the
/// scrollable axis. `MouseScrollUnit::Line` deltas (typical hardware
/// mice) get this scaled directly; `Pixel` deltas (touchpads /
/// high-resolution wheels) are passed through 1:1.
const SCROLL_LINE_PX: f32 = 60.0;

// ── Resources / phase enum ───────────────────────────────────────────────────

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum DraftPhase {
    Drafting,
    Deckbuilding,
    OpponentSelect,
}

/// Which view the user is currently looking at on the drafting
/// screen. The pack tab shows the current 15-card booster (large
/// tiles, click to pick); the picks tab shows everything they've
/// drafted so far (smaller tiles, view-only).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum DraftTab {
    #[default]
    Pack,
    Picks,
}

/// How the pack tiles are visually sorted. `PackOrder` preserves the
/// pack's natural order (the order generated by `generate_pack`);
/// the others reorder the displayed tiles. The underlying pack vec
/// is *never* reordered — `PackCardButton.pack_index` still points
/// to the original slot, so picks remain correct regardless of sort.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum PackSort {
    #[default]
    PackOrder,
    /// W → U → B → R → G → multicolor → colorless. Lands sort after
    /// non-lands within their color bucket.
    Color,
    /// Mana value ascending (0 first). Ties broken on name.
    ManaValue,
    /// Creatures first, then Instant/Sorcery, then other noncreature
    /// spells, then Land. A reasonable curve/role view.
    CardType,
    /// Alphabetical by card name.
    Name,
}

impl PackSort {
    const ALL: [PackSort; 5] = [
        PackSort::PackOrder,
        PackSort::Color,
        PackSort::ManaValue,
        PackSort::CardType,
        PackSort::Name,
    ];

    fn label(self) -> &'static str {
        match self {
            PackSort::PackOrder => "Pack",
            PackSort::Color => "Color",
            PackSort::ManaValue => "CMC",
            PackSort::CardType => "Type",
            PackSort::Name => "Name",
        }
    }
}

/// In-progress draft state. Spawned `OnEnter(AppState::Drafting)`,
/// removed `OnExit`. Owns the per-seat pack + pick piles for the
/// drafting phase and the staged main / sideboard / basics during
/// deckbuilding.
#[derive(Resource)]
pub struct DraftSession {
    pub pool: Vec<CardFactory>,
    /// Which format the draft is for. Determines both the pool the
    /// packs sample from (see `DraftSession::new`) and the label shown
    /// in the draft header.
    pub format: MatchFormat,
    pub phase: DraftPhase,

    // Drafting state
    pub user_seat: usize,
    pub pack_round: u32,
    pub pick_in_round: u32,
    pub packs: Vec<Vec<CardFactory>>,
    pub picks: Vec<Vec<CardFactory>>,
    pub current_tab: DraftTab,
    /// Display-only sort applied to the current user pack. Stored on
    /// the session so it persists across picks within the same draft.
    pub pack_sort: PackSort,

    // Deckbuilding state (only populated once draft completes)
    pub main: Vec<CardFactory>,
    pub sideboard: Vec<CardFactory>,
    pub basics: HashMap<ManaColor, u32>,
    pub player_colors: [ManaColor; 2],

    // Opponent select
    pub chosen_opponent: Option<usize>,
}

impl DraftSession {
    /// Build a fresh 8-seat draft pod for `format`. Currently only Cube
    /// and Sos are draftable — other formats fall back to the Cube pool
    /// since they don't have a curated draft set yet.
    pub fn new(format: MatchFormat) -> Self {
        let mut rng = rand::rng();
        let pool_kind = pool_for_format(format);
        let pool = pool_kind.factories();
        let packs: Vec<Vec<CardFactory>> = (0..POD_SIZE)
            .map(|_| pool_kind.generate_pack(&pool, &mut rng))
            .collect();
        let picks: Vec<Vec<CardFactory>> = (0..POD_SIZE).map(|_| Vec::new()).collect();
        Self {
            pool,
            format,
            phase: DraftPhase::Drafting,
            user_seat: 0,
            pack_round: 1,
            pick_in_round: 1,
            packs,
            picks,
            current_tab: DraftTab::Pack,
            pack_sort: PackSort::default(),
            main: Vec::new(),
            sideboard: Vec::new(),
            basics: HashMap::new(),
            player_colors: [ManaColor::White, ManaColor::Blue],
            chosen_opponent: None,
        }
    }

    pub fn user_pack(&self) -> &[CardFactory] {
        &self.packs[self.user_seat]
    }

    /// Advance one pick: user picks `user_pack_index`, all 7 bots
    /// auto-pick from their packs, then packs pass according to the
    /// current round's direction. If packs empty out, opens the next
    /// round of packs (or transitions phases on round 4).
    pub fn process_user_pick(&mut self, user_pack_index: usize) {
        if user_pack_index >= self.packs[self.user_seat].len() {
            return;
        }
        // 1. User picks.
        let card = self.packs[self.user_seat].remove(user_pack_index);
        self.picks[self.user_seat].push(card);

        // 2. Each bot auto-picks from its current pack.
        for seat in 0..POD_SIZE {
            if seat == self.user_seat {
                continue;
            }
            let pack = &self.packs[seat];
            if let Some(idx) = bot_pick(pack, &self.picks[seat]) {
                let card = self.packs[seat].remove(idx);
                self.picks[seat].push(card);
            }
        }

        // 3. Pass packs (left for rounds 1 + 3, right for round 2),
        //    or open new packs if all packs are empty.
        let any_card_left = self.packs.iter().any(|p| !p.is_empty());
        if any_card_left {
            self.pass_packs();
            self.pick_in_round += 1;
        } else {
            // Round complete.
            self.pack_round += 1;
            self.pick_in_round = 1;
            if self.pack_round > PACKS_PER_SEAT {
                self.transition_to_deckbuilding();
            } else {
                self.open_new_round();
            }
        }
    }

    fn pass_packs(&mut self) {
        // Round 1 + 3: pass left  (seat N → seat N-1).
        // Round 2: pass right     (seat N → seat N+1).
        // Indexing-wise, "pass left" means seat N's pack moves to
        // seat N-1's hands, so we rotate the `packs` vec right (the
        // pack that was at index N ends up at index N-1).
        let pass_left = self.pack_round != 2;
        if pass_left {
            self.packs.rotate_left(1);
        } else {
            self.packs.rotate_right(1);
        }
    }

    fn open_new_round(&mut self) {
        let mut rng = rand::rng();
        let pool_kind = pool_for_format(self.format);
        for pack in self.packs.iter_mut() {
            *pack = pool_kind.generate_pack(&self.pool, &mut rng);
        }
    }

    fn transition_to_deckbuilding(&mut self) {
        // Auto-suggest main + sideboard split from the user's picks.
        let user_picks = self.picks[self.user_seat].clone();
        let (suggested_main, suggested_sb) = suggest_main_deck(&user_picks, 23);
        self.main = suggested_main;
        self.sideboard = suggested_sb;
        self.player_colors = top_two_colors(&self.picks[self.user_seat]);
        self.basics = suggest_basic_split(&self.main, self.player_colors, 17);
        self.phase = DraftPhase::Deckbuilding;
    }

    /// Move card at `index` from main deck to sideboard.
    pub fn move_to_sideboard(&mut self, index: usize) {
        if index < self.main.len() {
            let card = self.main.remove(index);
            self.sideboard.push(card);
            self.refresh_basics_suggestion();
        }
    }

    /// Move card at `index` from sideboard to main deck.
    pub fn move_to_main(&mut self, index: usize) {
        if index < self.sideboard.len() {
            let card = self.sideboard.remove(index);
            self.main.push(card);
            self.refresh_basics_suggestion();
        }
    }

    /// Adjust basic-land count for one color. `delta` may be negative
    /// (saturating clamp at zero, no upper bound).
    pub fn adjust_basics(&mut self, color: ManaColor, delta: i32) {
        let current = self.basics.get(&color).copied().unwrap_or(0) as i32;
        let next = (current + delta).max(0) as u32;
        self.basics.insert(color, next);
    }

    /// Re-suggest basic split after a deckbuild edit. Called whenever
    /// the user moves a card in/out of main — keeps the basic count
    /// in sync with the new main deck's color requirements. The user
    /// can override afterwards via the +/- buttons; this just re-bases
    /// the auto-suggestion.
    fn refresh_basics_suggestion(&mut self) {
        // Preserve the currently-chosen basic colors but re-weight
        // them. The user's chosen color split (player_colors) is
        // sticky — we don't re-pick top_two_colors mid-build.
        let total_basics: u32 = self.basics.values().sum();
        let target = if total_basics == 0 { 17 } else { total_basics };
        self.basics = suggest_basic_split(&self.main, self.player_colors, target);
    }

    /// Total cards in main deck once basics are added.
    pub fn main_total(&self) -> u32 {
        self.main.len() as u32 + self.basics.values().copied().sum::<u32>()
    }

    /// Build the final shuffled deck list (main spells + basics) for
    /// the player. Applied at "Play Match" time.
    pub fn build_player_deck(&self) -> Vec<CardFactory> {
        let mut deck: Vec<CardFactory> = self.main.clone();
        for (&color, &count) in &self.basics {
            let basic = basic_land_factory(color);
            for _ in 0..count {
                deck.push(basic);
            }
        }
        enforce_copy_cap(deck)
    }

    /// Build a deck for an opponent bot seat. Same auto-suggestion
    /// pipeline used for the player's initial main split, but applied
    /// to the bot's own picks.
    pub fn build_opponent_deck(&self, seat: usize) -> (Vec<CardFactory>, [ManaColor; 2]) {
        let picks = &self.picks[seat];
        let (main, _sb) = suggest_main_deck(picks, 23);
        let colors = top_two_colors(picks);
        let basics = suggest_basic_split(&main, colors, 17);
        let mut deck = main;
        for (color, count) in basics {
            let basic = basic_land_factory(color);
            for _ in 0..count {
                deck.push(basic);
            }
        }
        (enforce_copy_cap(deck), colors)
    }
}

// ── Marker components ────────────────────────────────────────────────────────

#[derive(Component)]
struct DraftRoot;

#[derive(Component, Clone, Copy)]
struct PackCardButton {
    pack_index: usize,
}

#[derive(Component, Clone, Copy)]
struct DraftTabButton(DraftTab);

#[derive(Component, Clone, Copy)]
struct PackSortButton(PackSort);

#[derive(Component, Clone, Copy)]
struct DeckbuildCardButton {
    in_main: bool,
    index: usize,
}

#[derive(Component, Clone, Copy)]
struct BasicAdjustButton {
    color: ManaColor,
    delta: i32,
}

#[derive(Component, Clone, Copy)]
struct OpponentChoiceButton {
    seat: usize,
}

#[derive(Component)]
struct ConfirmDeckButton;

#[derive(Component)]
struct PlayMatchButton;

#[derive(Component)]
struct DraftBackToMenuButton;

/// Marker for nodes that respond to mouse-wheel scrolling. Carries no
/// data — the wheel handler queries `(&DraftScrollable, &mut
/// ScrollPosition, &ComputedNode, &GlobalTransform)` and routes the
/// scroll delta to whichever scrollable's bounds contain the cursor.
#[derive(Component)]
struct DraftScrollable;

/// Stamped onto every pack-card tile + picks-tab tile so the
/// alt-hover tooltip can read which card the cursor is over without
/// re-walking the pack vec. The name is the printed front-face name
/// (matching `CardDefinition.name`).
#[derive(Component, Clone)]
struct DraftCardName(String);

/// Floating-tooltip text node that follows the cursor while the user
/// holds Alt and hovers a draft card tile. Spawned once per Drafting
/// session by `enter_drafting`; updated by `update_draft_alt_tooltip`.
/// Hidden (Display::None) when Alt is released or no tile is hovered.
#[derive(Component)]
struct DraftAltTooltip;

// ── Plugin ───────────────────────────────────────────────────────────────────

pub struct DraftPlugin;

impl Plugin for DraftPlugin {
    fn build(&self, app: &mut App) {
        app.init_resource::<LastDraftWindowSize>()
            .add_systems(OnEnter(AppState::Drafting), enter_drafting)
            .add_systems(OnExit(AppState::Drafting), exit_drafting)
            .add_systems(
                Update,
                (
                    refresh_phase_ui,
                    handle_pack_clicks,
                    handle_tab_clicks,
                    handle_sort_clicks,
                    handle_deckbuild_clicks,
                    handle_basic_buttons,
                    handle_confirm_deck,
                    handle_opponent_clicks,
                    handle_play_match,
                    handle_back_to_menu,
                    handle_draft_scroll,
                    update_draft_alt_tooltip,
                )
                    .run_if(in_state(AppState::Drafting)),
            );
    }
}

// ── Lifecycle ────────────────────────────────────────────────────────────────

/// Compute the optimal pack-card width for `n_cards` laid out in a
/// flex-wrap grid against a `window` of the given logical size.
///
/// Algorithm: for each candidate column count `cols ∈ [1, n_cards]`,
/// figure out the largest card that fits both horizontally (`cols`
/// cards plus `cols-1` gutters across the available width) and
/// vertically (`ceil(n_cards / cols)` rows of cards plus gutters
/// within the available height, accounting for the card's 63:88
/// aspect ratio). Pick the column count that maximizes card width,
/// then clamp to `[PACK_CARD_W_MIN, PACK_CARD_W_MAX]`.
///
/// Why this matters: a pack starts with 15 cards but shrinks each
/// pick. With a static 170px tile a half-emptied pack ended up with
/// an awkward ~3-card row at top and a sea of empty space below. The
/// dynamic sizing keeps the grid taut as the pack drains.
fn compute_pack_card_width(window: Vec2, n_cards: usize) -> f32 {
    if n_cards == 0 {
        return PACK_CARD_W_MIN;
    }
    let avail_w = (window.x - PACK_GRID_PADDING_PX).max(PACK_CARD_W_MIN);
    let avail_h = (window.y - PACK_GRID_CHROME_PX - PACK_GRID_PADDING_PX).max(PACK_CARD_W_MIN);
    let mut best = PACK_CARD_W_MIN;
    for cols in 1..=n_cards {
        let rows = n_cards.div_ceil(cols) as f32;
        let cols_f = cols as f32;
        let w_from_width = (avail_w - (cols_f - 1.0) * PACK_GRID_GAP_PX) / cols_f;
        let h_from_height = (avail_h - (rows - 1.0) * PACK_GRID_GAP_PX) / rows;
        let w_from_height = h_from_height / CARD_ASPECT_H_OVER_W;
        let candidate = w_from_width.min(w_from_height);
        if candidate > best {
            best = candidate;
        }
    }
    best.clamp(PACK_CARD_W_MIN, PACK_CARD_W_MAX)
}

/// Map `MatchFormat` → engine `DraftPool`. Modern / Commander have no
/// curated draft pool; they fall back to Cube so the menu's "Draft"
/// button always produces something playable.
fn pool_for_format(format: MatchFormat) -> DraftPool {
    match format {
        MatchFormat::Sos => DraftPool::Sos,
        MatchFormat::Cube | MatchFormat::Modern | MatchFormat::Commander => DraftPool::Cube,
    }
}

fn enter_drafting(
    mut commands: Commands,
    pending: Res<PendingDraftFormat>,
    ui_fonts: Res<UiFonts>,
) {
    commands.insert_resource(DraftSession::new(pending.0));
    // Spawn the alt-hover tooltip once. Lives as a top-layer absolute
    // node — `update_draft_alt_tooltip` updates its position and text
    // each frame and toggles its `Display` based on hover + Alt state.
    commands.spawn((
        DraftAltTooltip,
        Text::new(""),
        ui_fonts.tf(15.0),
        TextColor(theme::TEXT_PRIMARY),
        BackgroundColor(theme::PANEL_BG_RAISED),
        Node {
            position_type: PositionType::Absolute,
            left: Val::Px(0.0),
            top: Val::Px(0.0),
            padding: UiRect::axes(Val::Px(8.0), Val::Px(4.0)),
            display: Display::None,
            ..default()
        },
        Pickable::IGNORE,
        // ZIndex isn't strictly necessary for top-layer nodes since
        // PositionType::Absolute already escapes the flex flow, but
        // bumping it ensures the tooltip wins over a freshly-spawned
        // grid that lands on a higher stacking context.
        GlobalZIndex(100),
    ));
}

fn exit_drafting(
    mut commands: Commands,
    root: Query<Entity, With<DraftRoot>>,
    tooltip: Query<Entity, With<DraftAltTooltip>>,
) {
    commands.remove_resource::<DraftSession>();
    for e in &root {
        commands.entity(e).despawn();
    }
    for e in &tooltip {
        commands.entity(e).despawn();
    }
}

// ── Render dispatch ──────────────────────────────────────────────────────────

/// Re-spawn the draft UI when the phase changes (or on first frame).
/// Also re-spawns the drafting / deckbuilding screens on every pick
/// so the live state (current pack, main deck, basics) stays in sync.
/// Cheap because each phase's tree is at most ~70 entities.
/// Cached window size from the previous frame's draft UI refresh, used
/// to detect resizes and force a grid re-spawn even when `DraftSession`
/// itself is unchanged. Floored to integer pixels to avoid endless
/// re-spawning from sub-pixel layout jitter.
#[derive(Resource, Default, Clone, Copy, PartialEq, Eq)]
struct LastDraftWindowSize {
    w: i32,
    h: i32,
}

fn refresh_phase_ui(
    mut commands: Commands,
    session: Option<Res<DraftSession>>,
    asset_server: Res<AssetServer>,
    ui_fonts: Res<UiFonts>,
    windows: Query<&Window>,
    mut last_size: ResMut<LastDraftWindowSize>,
    existing: Query<Entity, With<DraftRoot>>,
) {
    let Some(session) = session else { return };
    let window_size = windows
        .single()
        .map(|w| Vec2::new(w.width(), w.height()))
        .unwrap_or(Vec2::new(1280.0, 720.0));
    let snap = LastDraftWindowSize {
        w: window_size.x as i32,
        h: window_size.y as i32,
    };
    let resized = *last_size != snap;
    let stale = existing.is_empty();
    if !session.is_changed() && !stale && !resized {
        return;
    }
    *last_size = snap;
    for e in &existing {
        commands.entity(e).despawn();
    }
    match session.phase {
        DraftPhase::Drafting => {
            spawn_drafting_screen(&mut commands, &asset_server, &ui_fonts, &session, window_size)
        }
        DraftPhase::Deckbuilding => {
            spawn_deckbuilding_screen(&mut commands, &asset_server, &ui_fonts, &session)
        }
        DraftPhase::OpponentSelect => {
            spawn_opponent_select_screen(&mut commands, &asset_server, &ui_fonts, &session)
        }
    }
}

// ── Drafting screen ─────────────────────────────────────────────────────────

fn spawn_drafting_screen(
    commands: &mut Commands,
    asset_server: &AssetServer,
    ui_fonts: &UiFonts,
    session: &DraftSession,
    window_size: Vec2,
) {
    let root = spawn_root(commands);
    let user_picks = &session.picks[session.user_seat];
    commands
        .entity(root)
        .with_children(|root| {
            // ── Header: counters on the left, tab toggle on the right ──
            root.spawn((
                Node {
                    width: Val::Percent(100.0),
                    padding: UiRect::axes(Val::Px(20.0), Val::Px(12.0)),
                    flex_direction: FlexDirection::Row,
                    justify_content: JustifyContent::SpaceBetween,
                    align_items: AlignItems::Center,
                    column_gap: Val::Px(20.0),
                    ..default()
                },
                BackgroundColor(theme::PANEL_BG_RAISED),
                Pickable::IGNORE,
            ))
            .with_children(|h| {
                h.spawn((
                    Node {
                        flex_direction: FlexDirection::Column,
                        row_gap: Val::Px(2.0),
                        ..default()
                    },
                    Pickable::IGNORE,
                ))
                .with_children(|col| {
                    col.spawn((
                        Text::new(format!(
                            "{} Draft — Pack {}/{}, Pick {}/{}",
                            format_label(session.format),
                            session.pack_round,
                            PACKS_PER_SEAT,
                            session.pick_in_round,
                            PACK_SIZE,
                        )),
                        ui_fonts.tf(22.0),
                        TextColor(theme::ACCENT_GOLD),
                        Pickable::IGNORE,
                    ));
                    col.spawn((
                        Text::new(format!("Picked {} cards", user_picks.len())),
                        ui_fonts.tf(14.0),
                        TextColor(theme::TEXT_BODY),
                        Pickable::IGNORE,
                    ));
                });

                // Right-hand controls: pack sort toggles + tab toggle.
                h.spawn((
                    Node {
                        flex_direction: FlexDirection::Column,
                        align_items: AlignItems::FlexEnd,
                        row_gap: Val::Px(6.0),
                        ..default()
                    },
                    Pickable::IGNORE,
                ))
                .with_children(|col| {
                    // Sort-mode toggle row — only meaningful on the
                    // Pack tab, but kept visible always so the user
                    // can pre-set the sort before switching tabs.
                    col.spawn((
                        Node {
                            flex_direction: FlexDirection::Row,
                            column_gap: Val::Px(4.0),
                            ..default()
                        },
                        Pickable::IGNORE,
                    ))
                    .with_children(|sorts| {
                        sorts.spawn((
                            Text::new("Sort:"),
                            ui_fonts.tf(12.0),
                            TextColor(theme::TEXT_BODY),
                            Node {
                                margin: UiRect::right(Val::Px(4.0)),
                                ..default()
                            },
                            Pickable::IGNORE,
                        ));
                        for sort in PackSort::ALL {
                            spawn_sort_button(sorts, ui_fonts, sort, session.pack_sort);
                        }
                    });

                    // Tab toggle: Pack | Picks
                    col.spawn((
                        Node {
                            flex_direction: FlexDirection::Row,
                            column_gap: Val::Px(6.0),
                            ..default()
                        },
                        Pickable::IGNORE,
                    ))
                    .with_children(|tabs| {
                        spawn_tab_button(tabs, ui_fonts, "Pack", DraftTab::Pack, session.current_tab);
                        spawn_tab_button(
                            tabs,
                            ui_fonts,
                            &format!("Picks ({})", user_picks.len()),
                            DraftTab::Picks,
                            session.current_tab,
                        );
                    });
                });
            });

            // ── Body: scrollable, fills remaining vertical space ──
            // No `Pickable::IGNORE` here — the scroll-wheel handler
            // needs to find this node by cursor position. Children
            // (cards, tab buttons) still receive clicks via Bevy's
            // standard topmost-pick UI bubbling.
            root.spawn((
                Node {
                    flex_grow: 1.0,
                    width: Val::Percent(100.0),
                    overflow: Overflow::scroll_y(),
                    ..default()
                },
                ScrollPosition::default(),
                DraftScrollable,
            ))
            .with_children(|body| {
                match session.current_tab {
                    DraftTab::Pack => spawn_pack_grid(body, asset_server, session, window_size),
                    DraftTab::Picks => spawn_picks_grid(body, asset_server, ui_fonts, user_picks),
                }
            });

            // ── Stats footer: always visible, summarises user's picks ──
            spawn_stats_footer(root, ui_fonts, user_picks);
        });
}

fn spawn_pack_grid(
    body: &mut ChildSpawnerCommands,
    asset_server: &AssetServer,
    session: &DraftSession,
    window_size: Vec2,
) {
    let pack = session.user_pack();
    let card_w = compute_pack_card_width(window_size, pack.len());
    // Build a display order over the *original* pack indices so the
    // PackCardButton.pack_index attached to each tile still maps to
    // the right slot in `session.packs[user_seat]`. Sorting is a view
    // transform, not a data transform.
    let order = sorted_pack_indices(pack, session.pack_sort);
    body.spawn((
        Node {
            flex_direction: FlexDirection::Row,
            flex_wrap: FlexWrap::Wrap,
            column_gap: Val::Px(PACK_GRID_GAP_PX),
            row_gap: Val::Px(PACK_GRID_GAP_PX),
            padding: UiRect::all(Val::Px(20.0)),
            justify_content: JustifyContent::Center,
            align_content: AlignContent::Center,
            width: Val::Percent(100.0),
            min_height: Val::Px(window_size.y - PACK_GRID_CHROME_PX),
            ..default()
        },
        Pickable::IGNORE,
    ))
    .with_children(|grid| {
        for &i in &order {
            let factory = pack[i];
            let name = factory().name.to_string();
            spawn_pack_card_tile(grid, asset_server, &name, i, card_w);
        }
    });
}

/// Return the display order for `pack` under the given sort. Each
/// returned `usize` is an index into `pack` (so the caller can carry
/// the original `pack_index` onto the spawned tile for pick handling).
fn sorted_pack_indices(pack: &[CardFactory], sort: PackSort) -> Vec<usize> {
    let mut order: Vec<usize> = (0..pack.len()).collect();
    match sort {
        PackSort::PackOrder => {}
        PackSort::Color => {
            order.sort_by_key(|&i| color_sort_key(&pack[i]()));
        }
        PackSort::ManaValue => {
            order.sort_by_key(|&i| {
                let d = pack[i]();
                (d.cost.cmc(), d.name.to_string())
            });
        }
        PackSort::CardType => {
            order.sort_by_key(|&i| card_type_sort_key(&pack[i]()));
        }
        PackSort::Name => {
            order.sort_by_key(|&i| pack[i]().name.to_string());
        }
    }
    order
}

/// Sort key for `PackSort::Color`. Tuple shape ensures monocolor cards
/// in WUBRG order come first, followed by multicolor, then colorless,
/// then lands (which the player treats separately during deck-building).
/// Ties broken by mana value then name for stable presentation.
fn color_sort_key(def: &crabomination::card::CardDefinition) -> (u8, u8, u32, String) {
    use crabomination::card::CardType;
    use crabomination::mana::ManaSymbol;
    // Bucket 0..6: W, U, B, R, G, multicolor, colorless. Lands → 7.
    let is_land = def.card_types.contains(&CardType::Land);
    let mut colors = [false; 5];
    let color_idx = |c: ManaColor| match c {
        ManaColor::White => 0usize,
        ManaColor::Blue => 1,
        ManaColor::Black => 2,
        ManaColor::Red => 3,
        ManaColor::Green => 4,
    };
    for sym in &def.cost.symbols {
        match sym {
            ManaSymbol::Colored(c) | ManaSymbol::Phyrexian(c) => colors[color_idx(*c)] = true,
            ManaSymbol::Hybrid(a, b) => {
                colors[color_idx(*a)] = true;
                colors[color_idx(*b)] = true;
            }
            _ => {}
        }
    }
    let n_colors = colors.iter().filter(|&&b| b).count();
    let primary_bucket: u8 = if is_land {
        7
    } else if n_colors == 0 {
        6
    } else if n_colors >= 2 {
        5
    } else {
        // monocolor — bucket by which color is set.
        colors.iter().position(|&b| b).unwrap() as u8
    };
    // Secondary bucket: within "monocolor" or "multicolor" buckets,
    // creatures come before noncreature spells (a useful drafter view).
    let secondary: u8 = if def.card_types.contains(&CardType::Creature) {
        0
    } else if def.card_types.contains(&CardType::Instant)
        || def.card_types.contains(&CardType::Sorcery)
    {
        1
    } else {
        2
    };
    (primary_bucket, secondary, def.cost.cmc(), def.name.to_string())
}

/// Sort key for `PackSort::CardType`: Creature → IS spell → other
/// noncreature → Land. Ties broken by mana value then name.
fn card_type_sort_key(def: &crabomination::card::CardDefinition) -> (u8, u32, String) {
    use crabomination::card::CardType;
    let bucket: u8 = if def.card_types.contains(&CardType::Creature) {
        0
    } else if def.card_types.contains(&CardType::Instant)
        || def.card_types.contains(&CardType::Sorcery)
    {
        1
    } else if def.card_types.contains(&CardType::Land) {
        3
    } else {
        2
    };
    (bucket, def.cost.cmc(), def.name.to_string())
}

fn spawn_picks_grid(
    body: &mut ChildSpawnerCommands,
    asset_server: &AssetServer,
    ui_fonts: &UiFonts,
    picks: &[CardFactory],
) {
    if picks.is_empty() {
        body.spawn((
            Node {
                width: Val::Percent(100.0),
                padding: UiRect::all(Val::Px(40.0)),
                justify_content: JustifyContent::Center,
                ..default()
            },
            Pickable::IGNORE,
        ))
        .with_children(|p| {
            p.spawn((
                Text::new("No picks yet — pick a card from the Pack tab to start."),
                ui_fonts.tf(16.0),
                TextColor(theme::TEXT_SECONDARY),
                Pickable::IGNORE,
            ));
        });
        return;
    }
    body.spawn((
        Node {
            flex_direction: FlexDirection::Row,
            flex_wrap: FlexWrap::Wrap,
            column_gap: Val::Px(8.0),
            row_gap: Val::Px(8.0),
            padding: UiRect::all(Val::Px(20.0)),
            justify_content: JustifyContent::Center,
            width: Val::Percent(100.0),
            ..default()
        },
        Pickable::IGNORE,
    ))
    .with_children(|grid| {
        // Latest pick first — most useful order for tracking what
        // just landed in your pile.
        for factory in picks.iter().rev() {
            let name = factory().name;
            let path = scryfall::card_asset_path(name);
            let texture: Handle<Image> = asset_server.load(&path);
            // `Button` only to get the auto-injected `Interaction`
            // component — no click handler is registered for picks
            // tiles, so clicks are silently swallowed. This is what
            // gives the alt-hover tooltip something to query.
            grid.spawn((
                Button,
                Node {
                    width: Val::Px(PICKS_TAB_CARD_W),
                    height: Val::Px(PICKS_TAB_CARD_H),
                    ..default()
                },
                DraftCardName(name.to_string()),
            ))
            .with_children(|tile| {
                tile.spawn((
                    ImageNode { image: texture, ..default() },
                    Node {
                        width: Val::Percent(100.0),
                        height: Val::Percent(100.0),
                        ..default()
                    },
                    Pickable::IGNORE,
                ));
            });
        }
    });
}

fn spawn_tab_button(
    parent: &mut ChildSpawnerCommands,
    ui_fonts: &UiFonts,
    label: &str,
    tab: DraftTab,
    current: DraftTab,
) {
    let on = tab == current;
    parent
        .spawn((
            Button,
            Node {
                padding: UiRect::axes(Val::Px(18.0), Val::Px(8.0)),
                ..default()
            },
            BackgroundColor(if on { theme::BUTTON_WARN_BG } else { theme::FIELD_BG }),
            DraftTabButton(tab),
        ))
        .with_children(|b| {
            b.spawn((
                Text::new(label),
                ui_fonts.tf(14.0),
                TextColor(if on {
                    theme::TEXT_PRIMARY
                } else {
                    theme::TEXT_BODY
                }),
                Pickable::IGNORE,
            ));
        });
}

fn spawn_sort_button(
    parent: &mut ChildSpawnerCommands,
    ui_fonts: &UiFonts,
    sort: PackSort,
    current: PackSort,
) {
    let on = sort == current;
    parent
        .spawn((
            Button,
            Node {
                padding: UiRect::axes(Val::Px(10.0), Val::Px(4.0)),
                ..default()
            },
            BackgroundColor(if on { theme::BUTTON_WARN_BG } else { theme::FIELD_BG }),
            PackSortButton(sort),
        ))
        .with_children(|b| {
            b.spawn((
                Text::new(sort.label()),
                ui_fonts.tf(12.0),
                TextColor(if on {
                    theme::TEXT_PRIMARY
                } else {
                    theme::TEXT_BODY
                }),
                Pickable::IGNORE,
            ));
        });
}

fn spawn_pack_card_tile(
    parent: &mut ChildSpawnerCommands,
    asset_server: &AssetServer,
    card_name: &str,
    pack_index: usize,
    card_w: f32,
) {
    let path = scryfall::card_asset_path(card_name);
    let texture: Handle<Image> = asset_server.load(&path);
    let card_h = card_w * CARD_ASPECT_H_OVER_W;
    parent
        .spawn((
            Button,
            Node {
                width: Val::Px(card_w),
                height: Val::Px(card_h),
                ..default()
            },
            BackgroundColor(theme::FIELD_BG),
            PackCardButton { pack_index },
            // Card name is stamped onto the tile so the alt-hover
            // tooltip system can read it without re-walking the pack
            // vec. Survives sorts (the tile re-spawns, the new tile
            // carries the new name).
            DraftCardName(card_name.to_string()),
        ))
        .with_children(|tile| {
            tile.spawn((
                ImageNode { image: texture, ..default() },
                Node {
                    width: Val::Percent(100.0),
                    height: Val::Percent(100.0),
                    ..default()
                },
                Pickable::IGNORE,
            ));
        });
}

// ── Stats footer ────────────────────────────────────────────────────────────

/// Compact stats summary of the user's picks: color distribution
/// (W U B R G), curve histogram (0 / 1 / 2 / 3 / 4 / 5 / 6+ CMC),
/// and card-type breakdown (Creature / Spell / Land / Other).
/// Always visible across both tabs so the player can monitor their
/// shape while picking.
fn spawn_stats_footer(root: &mut ChildSpawnerCommands, ui_fonts: &UiFonts, picks: &[CardFactory]) {
    let stats = compute_pick_stats(picks);
    root.spawn((
        Node {
            width: Val::Percent(100.0),
            padding: UiRect::axes(Val::Px(20.0), Val::Px(10.0)),
            flex_direction: FlexDirection::Row,
            justify_content: JustifyContent::SpaceAround,
            align_items: AlignItems::Center,
            column_gap: Val::Px(24.0),
            ..default()
        },
        BackgroundColor(theme::PANEL_BG_SUNKEN),
        Pickable::IGNORE,
    ))
    .with_children(|footer| {
        // Colors block.
        footer
            .spawn((
                Node {
                    flex_direction: FlexDirection::Column,
                    align_items: AlignItems::Center,
                    row_gap: Val::Px(2.0),
                    ..default()
                },
                Pickable::IGNORE,
            ))
            .with_children(|col| {
                col.spawn((
                    Text::new("Colors"),
                    ui_fonts.tf(12.0),
                    TextColor(theme::TEXT_SECONDARY),
                    Pickable::IGNORE,
                ));
                col.spawn((
                    Node {
                        flex_direction: FlexDirection::Row,
                        column_gap: Val::Px(8.0),
                        ..default()
                    },
                    Pickable::IGNORE,
                ))
                .with_children(|row| {
                    for (label, count, color) in [
                        ("W", stats.colors[0], Color::srgb(0.95, 0.92, 0.78)),
                        ("U", stats.colors[1], Color::srgb(0.55, 0.75, 0.95)),
                        ("B", stats.colors[2], Color::srgb(0.65, 0.55, 0.75)),
                        ("R", stats.colors[3], Color::srgb(0.95, 0.55, 0.45)),
                        ("G", stats.colors[4], Color::srgb(0.55, 0.85, 0.55)),
                    ] {
                        row.spawn((
                            Text::new(format!("{label}:{count}")),
                            ui_fonts.tf(14.0),
                            TextColor(color),
                            Pickable::IGNORE,
                        ));
                    }
                });
            });

        // Curve block.
        footer
            .spawn((
                Node {
                    flex_direction: FlexDirection::Column,
                    align_items: AlignItems::Center,
                    row_gap: Val::Px(2.0),
                    ..default()
                },
                Pickable::IGNORE,
            ))
            .with_children(|col| {
                col.spawn((
                    Text::new("Curve"),
                    ui_fonts.tf(12.0),
                    TextColor(theme::TEXT_SECONDARY),
                    Pickable::IGNORE,
                ));
                col.spawn((
                    Node {
                        flex_direction: FlexDirection::Row,
                        column_gap: Val::Px(8.0),
                        ..default()
                    },
                    Pickable::IGNORE,
                ))
                .with_children(|row| {
                    for (label, count) in [
                        ("0", stats.curve[0]),
                        ("1", stats.curve[1]),
                        ("2", stats.curve[2]),
                        ("3", stats.curve[3]),
                        ("4", stats.curve[4]),
                        ("5", stats.curve[5]),
                        ("6+", stats.curve[6]),
                    ] {
                        row.spawn((
                            Text::new(format!("{label}:{count}")),
                            ui_fonts.tf(14.0),
                            TextColor(theme::TEXT_PRIMARY),
                            Pickable::IGNORE,
                        ));
                    }
                });
            });

        // Card-type block.
        footer
            .spawn((
                Node {
                    flex_direction: FlexDirection::Column,
                    align_items: AlignItems::Center,
                    row_gap: Val::Px(2.0),
                    ..default()
                },
                Pickable::IGNORE,
            ))
            .with_children(|col| {
                col.spawn((
                    Text::new("Types"),
                    ui_fonts.tf(12.0),
                    TextColor(theme::TEXT_SECONDARY),
                    Pickable::IGNORE,
                ));
                col.spawn((
                    Node {
                        flex_direction: FlexDirection::Row,
                        column_gap: Val::Px(8.0),
                        ..default()
                    },
                    Pickable::IGNORE,
                ))
                .with_children(|row| {
                    for (label, count) in [
                        ("Creatures", stats.creatures),
                        ("Spells", stats.spells),
                        ("Lands", stats.lands),
                        ("Other", stats.other),
                    ] {
                        row.spawn((
                            Text::new(format!("{label}:{count}")),
                            ui_fonts.tf(14.0),
                            TextColor(theme::TEXT_PRIMARY),
                            Pickable::IGNORE,
                        ));
                    }
                });
            });
    });
}

/// Aggregated stats for the picks footer. `colors` is a [W,U,B,R,G]
/// histogram of colored pip counts (so a `{W}{U}` card contributes 1
/// to W and 1 to U); `curve[i]` is the count of cards with CMC `i`,
/// or `≥6` in slot 6.
struct PickStats {
    colors: [u32; 5],
    curve: [u32; 7],
    creatures: u32,
    spells: u32,
    lands: u32,
    other: u32,
}

fn compute_pick_stats(picks: &[CardFactory]) -> PickStats {
    use crabomination::card::CardType;
    use crabomination::mana::ManaSymbol;
    let mut s = PickStats {
        colors: [0; 5],
        curve: [0; 7],
        creatures: 0,
        spells: 0,
        lands: 0,
        other: 0,
    };
    let color_idx = |c: ManaColor| match c {
        ManaColor::White => 0,
        ManaColor::Blue => 1,
        ManaColor::Black => 2,
        ManaColor::Red => 3,
        ManaColor::Green => 4,
    };
    for f in picks {
        let def = f();
        // Colored pips (hybrids count for both halves; Phyrexian
        // counts its colored side; generic / X / colorless skipped).
        for sym in &def.cost.symbols {
            match sym {
                ManaSymbol::Colored(c) | ManaSymbol::Phyrexian(c) => {
                    s.colors[color_idx(*c)] += 1;
                }
                ManaSymbol::Hybrid(a, b) => {
                    s.colors[color_idx(*a)] += 1;
                    s.colors[color_idx(*b)] += 1;
                }
                _ => {}
            }
        }
        // Curve — lands skipped; otherwise CMC bucketed 0..=5 then 6+.
        if !def.card_types.contains(&CardType::Land) {
            let cmc = def.cost.cmc().min(6) as usize;
            s.curve[cmc] += 1;
        }
        // Card type — multi-typed cards count as creature first
        // (creatures dominate gameplay decisions), then spell, land,
        // other.
        if def.card_types.contains(&CardType::Creature) {
            s.creatures += 1;
        } else if def.card_types.contains(&CardType::Instant)
            || def.card_types.contains(&CardType::Sorcery)
        {
            s.spells += 1;
        } else if def.card_types.contains(&CardType::Land) {
            s.lands += 1;
        } else {
            s.other += 1;
        }
    }
    s
}

// ── Deckbuilding screen ─────────────────────────────────────────────────────

fn spawn_deckbuilding_screen(
    commands: &mut Commands,
    asset_server: &AssetServer,
    ui_fonts: &UiFonts,
    session: &DraftSession,
) {
    let root = spawn_root(commands);
    commands
        .entity(root)
        .with_children(|root| {
            // Header.
            root.spawn((
                Node {
                    width: Val::Percent(100.0),
                    padding: UiRect::axes(Val::Px(20.0), Val::Px(12.0)),
                    flex_direction: FlexDirection::Row,
                    justify_content: JustifyContent::SpaceBetween,
                    align_items: AlignItems::Center,
                    ..default()
                },
                BackgroundColor(theme::PANEL_BG_RAISED),
                Pickable::IGNORE,
            ))
            .with_children(|h| {
                h.spawn((
                    Text::new("Build Your Deck"),
                    ui_fonts.tf(22.0),
                    TextColor(theme::ACCENT_GOLD),
                    Pickable::IGNORE,
                ));
                let total = session.main_total();
                let label = format!(
                    "Main: {} ({} spells + {} basics)  ·  Sideboard: {}",
                    total,
                    session.main.len(),
                    total as usize - session.main.len(),
                    session.sideboard.len(),
                );
                h.spawn((
                    Text::new(label),
                    ui_fonts.tf(14.0),
                    TextColor(theme::TEXT_BODY),
                    Pickable::IGNORE,
                ));
            });

            // Body: main + sideboard side by side.
            root.spawn((
                Node {
                    flex_direction: FlexDirection::Row,
                    column_gap: Val::Px(16.0),
                    padding: UiRect::all(Val::Px(16.0)),
                    width: Val::Percent(100.0),
                    flex_grow: 1.0,
                    ..default()
                },
                Pickable::IGNORE,
            ))
            .with_children(|body| {
                // Main panel.
                body.spawn((
                    Node {
                        flex_direction: FlexDirection::Column,
                        row_gap: Val::Px(8.0),
                        padding: UiRect::all(Val::Px(10.0)),
                        flex_basis: Val::Percent(60.0),
                        max_height: Val::Px(600.0),
                        overflow: Overflow::scroll_y(),
                        ..default()
                    },
                    BackgroundColor(theme::PANEL_BG_RAISED),
                    ScrollPosition::default(),
                    DraftScrollable,
                ))
                .with_children(|main| {
                    main.spawn((
                        Text::new("Main deck — click a card to move it to the sideboard"),
                        ui_fonts.tf(14.0),
                        TextColor(theme::TEXT_BODY),
                        Pickable::IGNORE,
                    ));
                    main.spawn((
                        Node {
                            flex_direction: FlexDirection::Row,
                            flex_wrap: FlexWrap::Wrap,
                            column_gap: Val::Px(6.0),
                            row_gap: Val::Px(6.0),
                            ..default()
                        },
                        Pickable::IGNORE,
                    ))
                    .with_children(|grid| {
                        for (i, factory) in session.main.iter().enumerate() {
                            spawn_deckbuild_tile(grid, asset_server, ui_fonts, factory().name, true, i);
                        }
                    });
                });

                // Sideboard + basic-land controls.
                body.spawn((
                    Node {
                        flex_direction: FlexDirection::Column,
                        row_gap: Val::Px(12.0),
                        flex_basis: Val::Percent(40.0),
                        ..default()
                    },
                    Pickable::IGNORE,
                ))
                .with_children(|right| {
                    // Basic land controls.
                    right.spawn((
                        Node {
                            flex_direction: FlexDirection::Column,
                            row_gap: Val::Px(6.0),
                            padding: UiRect::all(Val::Px(10.0)),
                            ..default()
                        },
                        BackgroundColor(theme::PANEL_BG_RAISED),
                        Pickable::IGNORE,
                    ))
                    .with_children(|panel| {
                        panel.spawn((
                            Text::new("Basic lands"),
                            ui_fonts.tf(14.0),
                            TextColor(theme::ACCENT_GOLD),
                            Pickable::IGNORE,
                        ));
                        for color in
                            [ManaColor::White, ManaColor::Blue, ManaColor::Black, ManaColor::Red, ManaColor::Green]
                        {
                            let count = session.basics.get(&color).copied().unwrap_or(0);
                            spawn_basic_row(panel, ui_fonts, color, count);
                        }
                    });

                    // Sideboard list.
                    right.spawn((
                        Node {
                            flex_direction: FlexDirection::Column,
                            row_gap: Val::Px(8.0),
                            padding: UiRect::all(Val::Px(10.0)),
                            max_height: Val::Px(400.0),
                            overflow: Overflow::scroll_y(),
                            ..default()
                        },
                        BackgroundColor(theme::PANEL_BG_RAISED),
                        ScrollPosition::default(),
                        DraftScrollable,
                    ))
                    .with_children(|sb| {
                        sb.spawn((
                            Text::new("Sideboard — click a card to move it to the main deck"),
                            ui_fonts.tf(13.0),
                            TextColor(theme::TEXT_BODY),
                            Pickable::IGNORE,
                        ));
                        sb.spawn((
                            Node {
                                flex_direction: FlexDirection::Row,
                                flex_wrap: FlexWrap::Wrap,
                                column_gap: Val::Px(6.0),
                                row_gap: Val::Px(6.0),
                                ..default()
                            },
                            Pickable::IGNORE,
                        ))
                        .with_children(|grid| {
                            for (i, factory) in session.sideboard.iter().enumerate() {
                                spawn_deckbuild_tile(grid, asset_server, ui_fonts, factory().name, false, i);
                            }
                        });
                    });

                    // Confirm button.
                    let confirm_enabled = session.main_total() >= 40;
                    let confirm_label = if confirm_enabled {
                        format!("Confirm Deck ({} cards) →", session.main_total())
                    } else {
                        format!(
                            "Need at least 40 cards (currently {})",
                            session.main_total()
                        )
                    };
                    right.spawn((
                        Button,
                        Node {
                            padding: UiRect::axes(Val::Px(20.0), Val::Px(10.0)),
                            justify_content: JustifyContent::Center,
                            ..default()
                        },
                        BackgroundColor(if confirm_enabled {
                            theme::ACCENT_GREEN
                        } else {
                            Color::srgba(0.30, 0.30, 0.35, 0.8)
                        }),
                        ConfirmDeckButton,
                    ))
                    .with_children(|b| {
                        b.spawn((
                            Text::new(confirm_label),
                            ui_fonts.tf(16.0),
                            TextColor(theme::TEXT_PRIMARY),
                            Pickable::IGNORE,
                        ));
                    });
                });
            });
        });
}

fn spawn_deckbuild_tile(
    parent: &mut ChildSpawnerCommands,
    asset_server: &AssetServer,
    _ui_fonts: &UiFonts,
    card_name: &str,
    in_main: bool,
    index: usize,
) {
    let path = scryfall::card_asset_path(card_name);
    let texture: Handle<Image> = asset_server.load(&path);
    parent
        .spawn((
            Button,
            Node {
                width: Val::Px(DECKBUILD_CARD_W),
                height: Val::Px(DECKBUILD_CARD_H),
                ..default()
            },
            BackgroundColor(theme::FIELD_BG),
            DeckbuildCardButton { in_main, index },
        ))
        .with_children(|tile| {
            tile.spawn((
                ImageNode { image: texture, ..default() },
                Node {
                    width: Val::Percent(100.0),
                    height: Val::Percent(100.0),
                    ..default()
                },
                Pickable::IGNORE,
            ));
        });
}

fn spawn_basic_row(parent: &mut ChildSpawnerCommands, ui_fonts: &UiFonts, color: ManaColor, count: u32) {
    let label = match color {
        ManaColor::White => "Plains",
        ManaColor::Blue => "Island",
        ManaColor::Black => "Swamp",
        ManaColor::Red => "Mountain",
        ManaColor::Green => "Forest",
    };
    parent
        .spawn((
            Node {
                flex_direction: FlexDirection::Row,
                column_gap: Val::Px(8.0),
                align_items: AlignItems::Center,
                ..default()
            },
            Pickable::IGNORE,
        ))
        .with_children(|row| {
            row.spawn((
                Text::new(format!("{label}:")),
                ui_fonts.tf(14.0),
                TextColor(theme::TEXT_BODY),
                Node { min_width: Val::Px(70.0), ..default() },
                Pickable::IGNORE,
            ));
            // Minus button.
            row.spawn((
                Button,
                Node {
                    width: Val::Px(28.0),
                    padding: UiRect::axes(Val::Px(8.0), Val::Px(2.0)),
                    justify_content: JustifyContent::Center,
                    ..default()
                },
                BackgroundColor(Color::srgba(0.40, 0.20, 0.20, 1.0)),
                BasicAdjustButton { color, delta: -1 },
            ))
            .with_children(|b| {
                b.spawn((
                    Text::new("−"),
                    ui_fonts.tf(16.0),
                    TextColor(theme::TEXT_PRIMARY),
                    Pickable::IGNORE,
                ));
            });
            // Count.
            row.spawn((
                Text::new(format!("{count}")),
                ui_fonts.tf(14.0),
                TextColor(theme::TEXT_PRIMARY),
                Node { min_width: Val::Px(28.0), ..default() },
                Pickable::IGNORE,
            ));
            // Plus button.
            row.spawn((
                Button,
                Node {
                    width: Val::Px(28.0),
                    padding: UiRect::axes(Val::Px(8.0), Val::Px(2.0)),
                    justify_content: JustifyContent::Center,
                    ..default()
                },
                BackgroundColor(Color::srgba(0.20, 0.40, 0.20, 1.0)),
                BasicAdjustButton { color, delta: 1 },
            ))
            .with_children(|b| {
                b.spawn((
                    Text::new("+"),
                    ui_fonts.tf(16.0),
                    TextColor(theme::TEXT_PRIMARY),
                    Pickable::IGNORE,
                ));
            });
        });
}

// ── Opponent select screen ──────────────────────────────────────────────────

fn spawn_opponent_select_screen(
    commands: &mut Commands,
    _asset_server: &AssetServer,
    ui_fonts: &UiFonts,
    session: &DraftSession,
) {
    let root = spawn_root(commands);
    commands
        .entity(root)
        .with_children(|root| {
            // Header.
            root.spawn((
                Node {
                    width: Val::Percent(100.0),
                    padding: UiRect::axes(Val::Px(20.0), Val::Px(14.0)),
                    flex_direction: FlexDirection::Column,
                    align_items: AlignItems::Center,
                    row_gap: Val::Px(6.0),
                    ..default()
                },
                BackgroundColor(theme::PANEL_BG_RAISED),
                Pickable::IGNORE,
            ))
            .with_children(|h| {
                h.spawn((
                    Text::new("Pick Your Opponent"),
                    ui_fonts.tf(24.0),
                    TextColor(theme::ACCENT_GOLD),
                    Pickable::IGNORE,
                ));
                h.spawn((
                    Text::new("Each bot drafted its own deck. Click one to play against them."),
                    ui_fonts.tf(14.0),
                    TextColor(theme::TEXT_BODY),
                    Pickable::IGNORE,
                ));
            });

            // Grid of 7 opponent buttons (seats 1..8, skipping the user).
            root.spawn((
                Node {
                    flex_direction: FlexDirection::Row,
                    flex_wrap: FlexWrap::Wrap,
                    column_gap: Val::Px(16.0),
                    row_gap: Val::Px(16.0),
                    padding: UiRect::all(Val::Px(20.0)),
                    justify_content: JustifyContent::Center,
                    ..default()
                },
                Pickable::IGNORE,
            ))
            .with_children(|grid| {
                for seat in 0..POD_SIZE {
                    if seat == session.user_seat {
                        continue;
                    }
                    let colors = top_two_colors(&session.picks[seat]);
                    let label = format!(
                        "Bot {seat}\n{}{}\n{} picks",
                        color_short(colors[0]),
                        color_short(colors[1]),
                        session.picks[seat].len()
                    );
                    grid.spawn((
                        Button,
                        Node {
                            width: Val::Px(180.0),
                            height: Val::Px(120.0),
                            padding: UiRect::all(Val::Px(12.0)),
                            justify_content: JustifyContent::Center,
                            align_items: AlignItems::Center,
                            ..default()
                        },
                        BackgroundColor(theme::FIELD_BG),
                        OpponentChoiceButton { seat },
                    ))
                    .with_children(|tile| {
                        tile.spawn((
                            Text::new(label),
                            ui_fonts.tf(16.0),
                            TextColor(theme::TEXT_PRIMARY),
                            Pickable::IGNORE,
                        ));
                    });
                }
            });

            // Selected-opponent confirmation row + Play button.
            if let Some(seat) = session.chosen_opponent {
                let colors = top_two_colors(&session.picks[seat]);
                root.spawn((
                    Node {
                        flex_direction: FlexDirection::Column,
                        align_items: AlignItems::Center,
                        row_gap: Val::Px(10.0),
                        padding: UiRect::all(Val::Px(20.0)),
                        ..default()
                    },
                    Pickable::IGNORE,
                ))
                .with_children(|row| {
                    row.spawn((
                        Text::new(format!(
                            "Selected: Bot {seat} ({}{})",
                            color_short(colors[0]),
                            color_short(colors[1]),
                        )),
                        ui_fonts.tf(18.0),
                        TextColor(theme::ACCENT_GOLD),
                        Pickable::IGNORE,
                    ));
                    row.spawn((
                        Button,
                        Node {
                            padding: UiRect::axes(Val::Px(28.0), Val::Px(12.0)),
                            ..default()
                        },
                        BackgroundColor(theme::ACCENT_GREEN),
                        PlayMatchButton,
                    ))
                    .with_children(|b| {
                        b.spawn((
                            Text::new("Play Match →"),
                            ui_fonts.tf(18.0),
                            TextColor(theme::TEXT_PRIMARY),
                            Pickable::IGNORE,
                        ));
                    });
                });
            }

            // Back-to-menu escape hatch.
            root.spawn((
                Node {
                    width: Val::Percent(100.0),
                    padding: UiRect::all(Val::Px(12.0)),
                    justify_content: JustifyContent::Center,
                    ..default()
                },
                Pickable::IGNORE,
            ))
            .with_children(|row| {
                row.spawn((
                    Button,
                    Node {
                        padding: UiRect::axes(Val::Px(16.0), Val::Px(8.0)),
                        ..default()
                    },
                    BackgroundColor(Color::srgba(0.30, 0.30, 0.35, 0.95)),
                    DraftBackToMenuButton,
                ))
                .with_children(|b| {
                    b.spawn((
                        Text::new("Back to Menu"),
                        ui_fonts.tf(14.0),
                        TextColor(theme::TEXT_PRIMARY),
                        Pickable::IGNORE,
                    ));
                });
            });
        });
}

// ── Click handlers ──────────────────────────────────────────────────────────

fn handle_pack_clicks(
    mut session: Option<ResMut<DraftSession>>,
    buttons: Query<(&Interaction, &PackCardButton), Changed<Interaction>>,
) {
    let Some(session) = session.as_mut() else { return };
    if !matches!(session.phase, DraftPhase::Drafting) {
        return;
    }
    // Picks tab is view-only; ignore pack clicks while it's active.
    if !matches!(session.current_tab, DraftTab::Pack) {
        return;
    }
    for (interaction, btn) in &buttons {
        if *interaction == Interaction::Pressed {
            session.process_user_pick(btn.pack_index);
            // One pick per click — bail to avoid double-consuming.
            return;
        }
    }
}

fn handle_tab_clicks(
    mut session: Option<ResMut<DraftSession>>,
    buttons: Query<(&Interaction, &DraftTabButton), Changed<Interaction>>,
) {
    let Some(session) = session.as_mut() else { return };
    if !matches!(session.phase, DraftPhase::Drafting) {
        return;
    }
    for (interaction, btn) in &buttons {
        if *interaction == Interaction::Pressed && session.current_tab != btn.0 {
            session.current_tab = btn.0;
            return;
        }
    }
}

fn handle_sort_clicks(
    mut session: Option<ResMut<DraftSession>>,
    buttons: Query<(&Interaction, &PackSortButton), Changed<Interaction>>,
) {
    let Some(session) = session.as_mut() else { return };
    if !matches!(session.phase, DraftPhase::Drafting) {
        return;
    }
    for (interaction, btn) in &buttons {
        if *interaction == Interaction::Pressed && session.pack_sort != btn.0 {
            session.pack_sort = btn.0;
            return;
        }
    }
}

fn handle_deckbuild_clicks(
    mut session: Option<ResMut<DraftSession>>,
    buttons: Query<(&Interaction, &DeckbuildCardButton), Changed<Interaction>>,
) {
    let Some(session) = session.as_mut() else { return };
    if !matches!(session.phase, DraftPhase::Deckbuilding) {
        return;
    }
    for (interaction, btn) in &buttons {
        if *interaction != Interaction::Pressed {
            continue;
        }
        if btn.in_main {
            session.move_to_sideboard(btn.index);
        } else {
            session.move_to_main(btn.index);
        }
        return;
    }
}

fn handle_basic_buttons(
    mut session: Option<ResMut<DraftSession>>,
    buttons: Query<(&Interaction, &BasicAdjustButton), Changed<Interaction>>,
) {
    let Some(session) = session.as_mut() else { return };
    if !matches!(session.phase, DraftPhase::Deckbuilding) {
        return;
    }
    for (interaction, btn) in &buttons {
        if *interaction == Interaction::Pressed {
            session.adjust_basics(btn.color, btn.delta);
            return;
        }
    }
}

fn handle_confirm_deck(
    mut session: Option<ResMut<DraftSession>>,
    buttons: Query<&Interaction, (Changed<Interaction>, With<ConfirmDeckButton>)>,
) {
    let Some(session) = session.as_mut() else { return };
    if !matches!(session.phase, DraftPhase::Deckbuilding) {
        return;
    }
    for interaction in &buttons {
        if *interaction == Interaction::Pressed && session.main_total() >= 40 {
            session.phase = DraftPhase::OpponentSelect;
            return;
        }
    }
}

fn handle_opponent_clicks(
    mut session: Option<ResMut<DraftSession>>,
    buttons: Query<(&Interaction, &OpponentChoiceButton), Changed<Interaction>>,
) {
    let Some(session) = session.as_mut() else { return };
    if !matches!(session.phase, DraftPhase::OpponentSelect) {
        return;
    }
    for (interaction, btn) in &buttons {
        if *interaction == Interaction::Pressed {
            session.chosen_opponent = Some(btn.seat);
            return;
        }
    }
}

fn handle_play_match(
    mut commands: Commands,
    session: Option<Res<DraftSession>>,
    mut next_state: ResMut<NextState<AppState>>,
    buttons: Query<&Interaction, (Changed<Interaction>, With<PlayMatchButton>)>,
) {
    let Some(session) = session else { return };
    if !matches!(session.phase, DraftPhase::OpponentSelect) {
        return;
    }
    let Some(opp_seat) = session.chosen_opponent else {
        return;
    };
    for interaction in &buttons {
        if *interaction == Interaction::Pressed {
            let player_deck = session.build_player_deck();
            let (opp_deck, opp_colors) = session.build_opponent_deck(opp_seat);
            let opponent_label = format!(
                "Bot {opp_seat} ({}{})",
                color_short(opp_colors[0]),
                color_short(opp_colors[1]),
            );
            commands.insert_resource(DraftedDecks {
                player_deck,
                opponent_deck: opp_deck,
                opponent_label,
            });
            next_state.set(AppState::InGame);
            return;
        }
    }
}

fn handle_back_to_menu(
    mut next_state: ResMut<NextState<AppState>>,
    buttons: Query<&Interaction, (Changed<Interaction>, With<DraftBackToMenuButton>)>,
) {
    for interaction in &buttons {
        if *interaction == Interaction::Pressed {
            next_state.set(AppState::Menu);
            return;
        }
    }
}

/// Mouse-wheel scrolling for `DraftScrollable` panels. Looks up the
/// cursor's window position, walks every scrollable node, and routes
/// the wheel delta to whichever node's screen-space bounds contain
/// the cursor. `ScrollPosition.y` is clamped at the lower bound; the
/// upper bound is left to Bevy's layout system, which trims
/// out-of-range scroll positions on the next frame.
///
/// Both `Line` and `Pixel` scroll units are supported — most desktop
/// mice emit `Line(±1)` per detent; trackpads / Wayland surfaces
/// emit `Pixel` deltas directly. The line variant is multiplied by
/// `SCROLL_LINE_PX` so each detent advances roughly one card row.
fn handle_draft_scroll(
    mut wheel: MessageReader<bevy::input::mouse::MouseWheel>,
    windows: Query<&Window>,
    mut scrollables: Query<
        (&ComputedNode, &GlobalTransform, &mut ScrollPosition),
        With<DraftScrollable>,
    >,
) {
    use bevy::input::mouse::MouseScrollUnit;
    // Aggregate this frame's deltas into a single scalar before the
    // bounds check, so a flurry of wheel events on the same frame
    // doesn't trip the per-event clamp pass repeatedly.
    let mut delta_px = 0.0f32;
    for ev in wheel.read() {
        delta_px += match ev.unit {
            MouseScrollUnit::Line => -ev.y * SCROLL_LINE_PX,
            MouseScrollUnit::Pixel => -ev.y,
        };
    }
    if delta_px == 0.0 {
        return;
    }
    let Ok(window) = windows.single() else { return };
    let Some(cursor) = window.cursor_position() else { return };
    for (computed, gtf, mut scroll) in &mut scrollables {
        // `ComputedNode::size()` is in logical pixels; the global
        // translation is the node's center in screen space.
        let size = computed.size();
        let center = gtf.translation().truncate();
        let half = size * 0.5;
        let inside = cursor.x >= center.x - half.x
            && cursor.x <= center.x + half.x
            && cursor.y >= center.y - half.y
            && cursor.y <= center.y + half.y;
        if !inside {
            continue;
        }
        // Clamp against content height. `ComputedNode` exposes the
        // content size only indirectly via `content_size()`; for
        // safety we just clamp the lower bound (no upper bound) and
        // let Bevy's layout system trim invalid values on the next
        // frame (see `ScrollPosition`'s docstring — the layout
        // system normalises out-of-range positions).
        let new_y = (scroll.0.y + delta_px).max(0.0);
        if (new_y - scroll.0.y).abs() > f32::EPSILON {
            scroll.0.y = new_y;
        }
        // Only the topmost hovered scrollable consumes the scroll —
        // bail to keep nested scrollables from double-scrolling on
        // the same wheel tick.
        return;
    }
}

// ── Helpers ─────────────────────────────────────────────────────────────────

fn spawn_root(commands: &mut Commands) -> Entity {
    commands
        .spawn((
            Node {
                position_type: PositionType::Absolute,
                left: Val::Px(0.0),
                top: Val::Px(0.0),
                width: Val::Percent(100.0),
                height: Val::Percent(100.0),
                flex_direction: FlexDirection::Column,
                ..default()
            },
            BackgroundColor(theme::PANEL_BG),
            DraftRoot,
        ))
        .id()
}

/// Float a tooltip near the cursor when the user holds Alt and hovers
/// a draft card tile. Shows the printed card name — the canonical use
/// case is identifying a tile whose Scryfall art failed to download
/// and renders as the cardback placeholder (so the player can read
/// what the card actually is). Both Pack-tab and Picks-tab tiles
/// carry `DraftCardName`, so this works in both views.
fn update_draft_alt_tooltip(
    keys: Res<ButtonInput<KeyCode>>,
    windows: Query<&Window>,
    hovered: Query<(&Interaction, &DraftCardName)>,
    mut tooltip: Query<(&mut Text, &mut Node), With<DraftAltTooltip>>,
) {
    let Ok((mut text, mut node)) = tooltip.single_mut() else { return };
    let alt_held = keys.pressed(KeyCode::AltLeft) || keys.pressed(KeyCode::AltRight);
    let hover_name = hovered
        .iter()
        .find(|(i, _)| matches!(**i, Interaction::Hovered | Interaction::Pressed))
        .map(|(_, name)| name.0.clone());
    match (alt_held, hover_name) {
        (true, Some(name)) => {
            *text = Text::new(name);
            node.display = Display::Flex;
            if let Ok(window) = windows.single()
                && let Some(cursor) = window.cursor_position()
            {
                // Offset slightly so the tooltip doesn't sit under the
                // cursor and steal hover hits from neighbouring tiles.
                node.left = Val::Px(cursor.x + 14.0);
                node.top = Val::Px(cursor.y + 14.0);
            }
        }
        _ => {
            node.display = Display::None;
        }
    }
}

fn format_label(format: MatchFormat) -> &'static str {
    match format {
        MatchFormat::Modern => "Modern",
        MatchFormat::Cube => "Cube",
        MatchFormat::Sos => "SoS",
        MatchFormat::Commander => "Commander",
    }
}


fn color_short(c: ManaColor) -> &'static str {
    match c {
        ManaColor::White => "W",
        ManaColor::Blue => "U",
        ManaColor::Black => "B",
        ManaColor::Red => "R",
        ManaColor::Green => "G",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pack_card_width_grows_as_pack_drains() {
        let win = Vec2::new(1920.0, 1080.0);
        let w15 = compute_pack_card_width(win, 15);
        let w8 = compute_pack_card_width(win, 8);
        let w3 = compute_pack_card_width(win, 3);
        let w1 = compute_pack_card_width(win, 1);
        assert!(w15 <= w8, "8-card pack should not shrink vs 15-card");
        assert!(w8 <= w3, "3-card pack should not shrink vs 8-card");
        assert!(w3 <= w1, "1-card pack should not shrink vs 3-card");
    }

    #[test]
    fn pack_card_width_grows_with_resolution() {
        let small = Vec2::new(1280.0, 720.0);
        let big = Vec2::new(2560.0, 1440.0);
        let w_small = compute_pack_card_width(small, 15);
        let w_big = compute_pack_card_width(big, 15);
        assert!(w_big >= w_small, "wider screen should grant at least as much card width");
    }

    #[test]
    fn pack_card_width_clamped() {
        // A single card on a huge screen should not exceed the max.
        let w = compute_pack_card_width(Vec2::new(4000.0, 4000.0), 1);
        assert!(w <= PACK_CARD_W_MAX);
        // 15 cards on a tiny window stays at the min.
        let w = compute_pack_card_width(Vec2::new(800.0, 600.0), 15);
        assert!(w >= PACK_CARD_W_MIN);
    }
}
