//! `sets` for this part: the core's helpers and hub sets, and this part's
//! own set modules.

pub use crabomination_catalog_core::sets::*;

#[path = "../../../src/sets/akh/mod.rs"]
pub mod akh;
#[path = "../../../src/sets/all/mod.rs"]
pub mod all;
#[path = "../../../src/sets/all2.rs"]
pub mod all2;
#[path = "../../../src/sets/ante.rs"]
pub mod ante;
#[path = "../../../src/sets/ap/mod.rs"]
pub mod ap;
#[path = "../../../src/sets/apc.rs"]
pub mod apc;
#[path = "../../../src/sets/apc2.rs"]
pub mod apc2;
#[path = "../../../src/sets/arc.rs"]
pub mod arc;
#[path = "../../../src/sets/arn/mod.rs"]
pub mod arn;
#[path = "../../../src/sets/atq.rs"]
pub mod atq;
#[path = "../../../src/sets/bfz/mod.rs"]
pub mod bfz;
#[path = "../../../src/sets/bng.rs"]
pub mod bng;
#[path = "../../../src/sets/bng2.rs"]
pub mod bng2;
#[path = "../../../src/sets/bng3.rs"]
pub mod bng3;
#[path = "../../../src/sets/bok.rs"]
pub mod bok;
#[path = "../../../src/sets/bok2.rs"]
pub mod bok2;
#[path = "../../../src/sets/bot.rs"]
pub mod bot;
#[path = "../../../src/sets/bro.rs"]
pub mod bro;
#[path = "../../../src/sets/c21.rs"]
pub mod c21;
#[path = "../../../src/sets/chk.rs"]
pub mod chk;
#[path = "../../../src/sets/chk2.rs"]
pub mod chk2;
#[path = "../../../src/sets/chk3.rs"]
pub mod chk3;
#[path = "../../../src/sets/clb.rs"]
pub mod clb;
#[path = "../../../src/sets/cn2.rs"]
pub mod cn2;
#[path = "../../../src/sets/cns.rs"]
pub mod cns;
#[path = "../../../src/sets/cns2.rs"]
pub mod cns2;
#[path = "../../../src/sets/cns3.rs"]
pub mod cns3;
#[path = "../../../src/sets/csp.rs"]
pub mod csp;
#[path = "../../../src/sets/curses.rs"]
pub mod curses;
#[path = "../../../src/sets/dgm/mod.rs"]
pub mod dgm;
#[path = "../../../src/sets/dis/mod.rs"]
pub mod dis;
#[path = "../../../src/sets/drk.rs"]
pub mod drk;
#[path = "../../../src/sets/drk2.rs"]
pub mod drk2;
#[path = "../../../src/sets/eoe.rs"]
pub mod eoe;
#[path = "../../../src/sets/eoe2.rs"]
pub mod eoe2;
#[path = "../../../src/sets/exo.rs"]
pub mod exo;
#[path = "../../../src/sets/exo2.rs"]
pub mod exo2;
#[path = "../../../src/sets/fem/mod.rs"]
pub mod fem;
#[path = "../../../src/sets/fin.rs"]
pub mod fin;
#[path = "../../../src/sets/fin2.rs"]
pub mod fin2;
#[path = "../../../src/sets/gpt/mod.rs"]
pub mod gpt;
#[path = "../../../src/sets/gtc.rs"]
pub mod gtc;
#[path = "../../../src/sets/gtc10.rs"]
pub mod gtc10;
#[path = "../../../src/sets/gtc11.rs"]
pub mod gtc11;
#[path = "../../../src/sets/gtc12.rs"]
pub mod gtc12;
#[path = "../../../src/sets/gtc13.rs"]
pub mod gtc13;
#[path = "../../../src/sets/gtc14.rs"]
pub mod gtc14;
#[path = "../../../src/sets/gtc15.rs"]
pub mod gtc15;
#[path = "../../../src/sets/gtc16.rs"]
pub mod gtc16;
#[path = "../../../src/sets/gtc17.rs"]
pub mod gtc17;
#[path = "../../../src/sets/gtc2.rs"]
pub mod gtc2;
#[path = "../../../src/sets/gtc3.rs"]
pub mod gtc3;
#[path = "../../../src/sets/gtc4.rs"]
pub mod gtc4;
#[path = "../../../src/sets/gtc5.rs"]
pub mod gtc5;
#[path = "../../../src/sets/gtc6.rs"]
pub mod gtc6;
#[path = "../../../src/sets/gtc7.rs"]
pub mod gtc7;
#[path = "../../../src/sets/gtc8.rs"]
pub mod gtc8;
#[path = "../../../src/sets/gtc9.rs"]
pub mod gtc9;
#[path = "../../../src/sets/hml.rs"]
pub mod hml;
#[path = "../../../src/sets/hml2.rs"]
pub mod hml2;
#[path = "../../../src/sets/hml3.rs"]
pub mod hml3;
#[path = "../../../src/sets/ice/mod.rs"]
pub mod ice;
#[path = "../../../src/sets/sok.rs"]
pub mod sok;
#[path = "../../../src/sets/sok2.rs"]
pub mod sok2;
#[path = "../../../src/sets/sok3.rs"]
pub mod sok3;
