//! `sets` for this part: the core's helpers and hub sets, and this part's
//! own set modules.

pub use crabomination_catalog_core::sets::*;

#[path = "../../../src/sets/inv/mod.rs"]
pub mod inv;
#[path = "../../../src/sets/jou.rs"]
pub mod jou;
#[path = "../../../src/sets/jou2.rs"]
pub mod jou2;
#[path = "../../../src/sets/jou3.rs"]
pub mod jou3;
#[path = "../../../src/sets/jud.rs"]
pub mod jud;
#[path = "../../../src/sets/jud2.rs"]
pub mod jud2;
#[path = "../../../src/sets/khm/mod.rs"]
pub mod khm;
#[path = "../../../src/sets/kld/mod.rs"]
pub mod kld;
#[path = "../../../src/sets/ktk/mod.rs"]
pub mod ktk;
#[path = "../../../src/sets/lci.rs"]
pub mod lci;
#[path = "../../../src/sets/leg.rs"]
pub mod leg;
#[path = "../../../src/sets/leg2.rs"]
pub mod leg2;
#[path = "../../../src/sets/leg3.rs"]
pub mod leg3;
#[path = "../../../src/sets/leg4.rs"]
pub mod leg4;
#[path = "../../../src/sets/leg5.rs"]
pub mod leg5;
#[path = "../../../src/sets/leg6.rs"]
pub mod leg6;
#[path = "../../../src/sets/leg7.rs"]
pub mod leg7;
#[path = "../../../src/sets/lgn.rs"]
pub mod lgn;
#[path = "../../../src/sets/m11/mod.rs"]
pub mod m11;
#[path = "../../../src/sets/m15.rs"]
pub mod m15;
#[path = "../../../src/sets/mbs.rs"]
pub mod mbs;
#[path = "../../../src/sets/mh3.rs"]
pub mod mh3;
#[path = "../../../src/sets/mh3b.rs"]
pub mod mh3b;
#[path = "../../../src/sets/mh3c.rs"]
pub mod mh3c;
#[path = "../../../src/sets/mh3d.rs"]
pub mod mh3d;
#[path = "../../../src/sets/mh3e.rs"]
pub mod mh3e;
#[path = "../../../src/sets/mir.rs"]
pub mod mir;
#[path = "../../../src/sets/mir2.rs"]
pub mod mir2;
#[path = "../../../src/sets/mir3.rs"]
pub mod mir3;
#[path = "../../../src/sets/mir4.rs"]
pub mod mir4;
#[path = "../../../src/sets/mir5.rs"]
pub mod mir5;
#[path = "../../../src/sets/mkm.rs"]
pub mod mkm;
#[path = "../../../src/sets/mkm2.rs"]
pub mod mkm2;
#[path = "../../../src/sets/mmq.rs"]
pub mod mmq;
#[path = "../../../src/sets/mmq2.rs"]
pub mod mmq2;
#[path = "../../../src/sets/mmq3.rs"]
pub mod mmq3;
#[path = "../../../src/sets/mmq4.rs"]
pub mod mmq4;
#[path = "../../../src/sets/mmq5.rs"]
pub mod mmq5;
#[path = "../../../src/sets/mmq6.rs"]
pub mod mmq6;
#[path = "../../../src/sets/mod_set/mod.rs"]
pub mod mod_set;
#[path = "../../../src/sets/nms.rs"]
pub mod nms;
#[path = "../../../src/sets/nms2.rs"]
pub mod nms2;
#[path = "../../../src/sets/nms3.rs"]
pub mod nms3;
#[path = "../../../src/sets/nms4.rs"]
pub mod nms4;
#[path = "../../../src/sets/nph.rs"]
pub mod nph;
