//! `sets` for this part: the core's helpers and hub sets, and this part's
//! own set modules.

pub use crabomination_catalog_core::sets::*;

#[path = "../../../src/sets/ody/mod.rs"]
pub mod ody;
#[path = "../../../src/sets/ogw/mod.rs"]
pub mod ogw;
#[path = "../../../src/sets/ohop.rs"]
pub mod ohop;
#[path = "../../../src/sets/ons.rs"]
pub mod ons;
#[path = "../../../src/sets/ons2.rs"]
pub mod ons2;
#[path = "../../../src/sets/ons3.rs"]
pub mod ons3;
#[path = "../../../src/sets/ons4.rs"]
pub mod ons4;
#[path = "../../../src/sets/pc2/mod.rs"]
pub mod pc2;
#[path = "../../../src/sets/pcy.rs"]
pub mod pcy;
#[path = "../../../src/sets/pcy2.rs"]
pub mod pcy2;
#[path = "../../../src/sets/pcy3.rs"]
pub mod pcy3;
#[path = "../../../src/sets/pcy4.rs"]
pub mod pcy4;
#[path = "../../../src/sets/pip.rs"]
pub mod pip;
#[path = "../../../src/sets/pls.rs"]
pub mod pls;
#[path = "../../../src/sets/pls2.rs"]
pub mod pls2;
#[path = "../../../src/sets/por/mod.rs"]
pub mod por;
#[path = "../../../src/sets/rav/mod.rs"]
pub mod rav;
#[path = "../../../src/sets/rna2.rs"]
pub mod rna2;
#[path = "../../../src/sets/rtr/mod.rs"]
pub mod rtr;
#[path = "../../../src/sets/scg.rs"]
pub mod scg;
#[path = "../../../src/sets/scg2.rs"]
pub mod scg2;
#[path = "../../../src/sets/shm.rs"]
pub mod shm;
#[path = "../../../src/sets/sth.rs"]
pub mod sth;
#[path = "../../../src/sets/ths/mod.rs"]
pub mod ths;
#[path = "../../../src/sets/tmp/mod.rs"]
pub mod tmp;
#[path = "../../../src/sets/tor.rs"]
pub mod tor;
#[path = "../../../src/sets/tor2.rs"]
pub mod tor2;
#[path = "../../../src/sets/uds.rs"]
pub mod uds;
#[path = "../../../src/sets/ulg.rs"]
pub mod ulg;
#[path = "../../../src/sets/unf.rs"]
pub mod unf;
#[path = "../../../src/sets/usg.rs"]
pub mod usg;
#[path = "../../../src/sets/usg2.rs"]
pub mod usg2;
#[path = "../../../src/sets/usg3.rs"]
pub mod usg3;
#[path = "../../../src/sets/vanguard.rs"]
pub mod vanguard;
#[path = "../../../src/sets/vis.rs"]
pub mod vis;
#[path = "../../../src/sets/vis2.rs"]
pub mod vis2;
#[path = "../../../src/sets/war.rs"]
pub mod war;
#[path = "../../../src/sets/wth.rs"]
pub mod wth;
#[path = "../../../src/sets/wth2.rs"]
pub mod wth2;
#[path = "../../../src/sets/wwk.rs"]
pub mod wwk;
#[path = "../../../src/sets/wwk2.rs"]
pub mod wwk2;
#[path = "../../../src/sets/xtra.rs"]
pub mod xtra;
#[path = "../../../src/sets/zen/mod.rs"]
pub mod zen;
#[path = "../../../src/sets/zen2.rs"]
pub mod zen2;
#[path = "../../../src/sets/zen3.rs"]
pub mod zen3;
