//! Frozen embedding-index assignment for [`super::encode::Vocab`].
//!
//! **Why this file exists.** `Vocab::sos_sealed()` used to derive its
//! indices from `draft::sos_draft_pool()` directly, in sorted-name order —
//! so adding one card to the SOS set shifted the index of every card that
//! sorts after it, and *every net trained before that addition became
//! wrong*. It failed loudly (the embedding row count no longer matched) for
//! the play net and silently for nothing, which is the only mercy in it:
//! all seven committed `deck-latest.safetensors` are 153 rows against a
//! live vocabulary of 164 and none of them can be loaded.
//!
//! **The contract now.** A name in [`VOCAB_SNAPSHOT`] owns index
//! `position + 1`, forever, whether or not it is still in the pool. A pool
//! name that is not in the snapshot is appended after it, in sorted order.
//! So a card addition — or a removal — grows the table at the end and never
//! moves an index a trained net depends on, and a net trained against a
//! smaller vocabulary can be zero-padded up to the current one instead of
//! being retired.
//!
//! **Do not reorder, remove, or edit an entry. Appending is the only safe
//! edit, and it is required, not tidying.** A pool card outside the
//! snapshot assigns itself an index so the build keeps working, but that
//! index is provisional: it comes from sorted order over the *unsnapshotted*
//! names, so a second card addition reshuffles it and reintroduces exactly
//! the defect this file closes, one generation later. Two additions is all
//! it takes. `encode`'s `vocab_covers_the_sos_pool` fails while any pool
//! name is unsnapshotted and prints the names to append — at the end of the
//! array, in the order `Vocab::sos_sealed()` gives them.
//!
//! Seeded 2026-08-24 from the then-current `Vocab::sos_sealed()`, which was
//! the sorted pool plus the five basics — so the seed *is* the mapping that
//! existed before this file, and `nets/champion.safetensors` (164 rows) is
//! unaffected by its introduction.
//!
//! **Appended 2026-08-30: the modern cube pool** (`cube::cube_pool_all`,
//! ~2,100 names) — the modern-pool track's first precondition, so a net
//! can tell Lightning Bolt from Emrakul before those decks ever enter a
//! training pool. Everything after "Zimone's Experiment" is that append;
//! [`FROZEN_VOCAB_SIZE`] stays pinned at the 2026-08-24 boundary so every
//! net trained since the freeze still pads. Two coverage tests now hold
//! the pools to this file (`vocab_covers_the_sos_pool`,
//! `vocab_covers_the_cube_pool`), and `the_freeze_boundary_is_pinned`
//! holds the boundary itself.

/// The names whose embedding indices are frozen. Index 0 is the reserved
/// unknown slot, so this list starts at index 1.
pub const VOCAB_SNAPSHOT: [&str; 2272] = [
    "Additive Evolution",
    "Adrix and Nev, Twincasters",
    "Ambitious Augmenter",
    "Applied Geometry",
    "Arcane Omens",
    "Archaeomancer",
    "Archaic's Agony",
    "Archmage Emeritus",
    "Ark of Hunger",
    "Arnyn, Deathbloom Botanist",
    "Artistic Process",
    "Ascendant Dustspeaker",
    "Aziza, Mage Tower Captain",
    "Banishing Betrayal",
    "Berta, Wise Extrapolator",
    "Blech, Loafing Pest",
    "Bogwater Lumaret",
    "Burrog Banemaker",
    "Burrog Barrage",
    "Campus Composer",
    "Cauldron of Essence",
    "Charging Strifeknight",
    "Chase Inspiration",
    "Chelonian Tackle",
    "Choreographed Sparks",
    "Codie, Vociferous Codex",
    "Colorstorm Stallion",
    "Daydream",
    "Decorum Dissertation",
    "Deluge Virtuoso",
    "Divergent Equation",
    "Dualcaster Mage",
    "Duel Tactics",
    "Eager Glyphmage",
    "Echocasting Symposium",
    "Efflorescence",
    "Elemental Mascot",
    "Emeritus of Ideation",
    "Ennis, Debate Moderator",
    "Environmental Scientist",
    "Essenceknit Scholar",
    "Fields of Strife",
    "Fix What's Broken",
    "Flow State",
    "Follow the Lumarets",
    "Foolish Fate",
    "Forest",
    "Forum Necroscribe",
    "Forum of Amity",
    "Fractal Anomaly",
    "Fractal Mascot",
    "Fractal Tender",
    "Fractalize",
    "Garrison Excavator",
    "Geometer's Arthropod",
    "Germination Practicum",
    "Glorious Decay",
    "Graduation Day",
    "Grapple with Death",
    "Grave Researcher",
    "Grim Haruspex",
    "Growth Curve",
    "Hardened Academic",
    "Homesickness",
    "Imperious Inkmage",
    "Improvisation Capstone",
    "Informed Inkwright",
    "Inkling Mascot",
    "Inkshape Demonstrator",
    "Interjection",
    "Island",
    "Lecturing Scornmage",
    "Library of Alexandria",
    "Library of Leng",
    "Living History",
    "Lluwen, Exchange Student",
    "Lorehold Charm",
    "Lorehold, the Historian",
    "Lumaret's Favor",
    "Magmablood Archaic",
    "Magus of the Library",
    "Mana Sculpt",
    "Masterful Flourish",
    "Melancholic Poet",
    "Mica, Reader of Ruins",
    "Mindful Biomancer",
    "Molten Note",
    "Moseo, Vein's New Dean",
    "Mountain",
    "Murmuring Mystic",
    "Muse's Encouragement",
    "Nita, Forum Conciliator",
    "Noxious Newt",
    "Old-Growth Educator",
    "Oracle's Restoration",
    "Paradox Gardens",
    "Paradox Surveyor",
    "Pest Mascot",
    "Plains",
    "Planar Engineering",
    "Practiced Offense",
    "Practiced Scrollsmith",
    "Primary Research",
    "Prismari Charm",
    "Prismari, the Inspiration",
    "Procrastinate",
    "Proctor's Gaze",
    "Professor Dellian Fel",
    "Quandrix, the Proof",
    "Rabid Attack",
    "Ral Zarek, Guest Lecturer",
    "Rapier Wit",
    "Rapturous Moment",
    "Rearing Embermare",
    "Rehearsed Debater",
    "Resonating Lute",
    "Restoration Seminar",
    "Rubble Rouser",
    "Shattered Acolyte",
    "Shopkeeper's Bane",
    "Silverquill Charm",
    "Silverquill, the Disputant",
    "Slumbering Trudge",
    "Snarl Song",
    "Sneering Shadewriter",
    "Snooping Page",
    "Soaring Stoneglider",
    "Social Snub",
    "Spectacle Summit",
    "Spectacular Skywhale",
    "Spirit Mascot",
    "Splatter Technique",
    "Stand Up for Yourself",
    "Startled Relic Sloth",
    "Steal the Show",
    "Stirring Honormancer",
    "Stirring Hopesinger",
    "Stone Docent",
    "Strife Scholar",
    "Studious First-Year",
    "Suspend Aggression",
    "Swamp",
    "Sylvan Library",
    "Tablet of Discovery",
    "Textbook Tabulator",
    "Thornfist Striker",
    "Titan's Grave",
    "Tome Blast",
    "Top of the Class",
    "Topiary Lecturer",
    "Tragedy Feaster",
    "Traumatic Critique",
    "Unsubtle Mockery",
    "Vicious Rivalry",
    "Wander Off",
    "Wild Hypothesis",
    "Wildgrowth Archaic",
    "Wilt in the Heat",
    "Witherbloom, the Balancer",
    "Withering Curse",
    "Zaffai and the Tempests",
    "Zealous Lorecaster",
    "Zimone's Experiment",
    // Modern cube pool, appended 2026-08-30. Everything above this line is
    // the 2026-08-24 SOS seed (`FROZEN_VOCAB_SIZE` boundary); everything
    // below appends in `Vocab::sos_sealed()` order. Append-only, as above.
    "Aberrant Manawurm",
    "Abigale, Poet Laureate",
    "Abrade",
    "Abstract Paintmage",
    "Abyssal Specter",
    "Abzan Battle Priest",
    "Abzan Falconer",
    "Accorder's Shield",
    "Acidic Slime",
    "Acidic Sliver",
    "Act of Treason",
    "Adanto Vanguard",
    "Adeline, Resplendent Cathar",
    "Admonition Angel",
    "Adorned Pouncer",
    "Adventurous Eater",
    "Aerial Predation",
    "Aerial Responder",
    "Aether Adept",
    "Aether Figment",
    "Aether Gust",
    "Aether Spellbomb",
    "Aether Vial",
    "Aetherflux Reservoir",
    "Aetherize",
    "Aftermath Analyst",
    "Agatha's Soul Cauldron",
    "Ahn-Crop Crasher",
    "Ainok Bond-Kin",
    "Ainok Survivalist",
    "Air Elemental",
    "Air Servant",
    "Ajani's Pridemate",
    "Ajani's Response",
    "Ajani's Welcome",
    "Akrasan Squire",
    "Akroma's Devoted",
    "Akroma's Vengeance",
    "Alive // Well",
    "All Is Dust",
    "Alley Assailant",
    "Alpine Grizzly",
    "Ambassador Oak",
    "Ambition's Cost",
    "Amped Raptor",
    "Amulet of Vigor",
    "Ancestral Recall",
    "Ancient Copper Dragon",
    "Ancient Craving",
    "Ancient Grudge",
    "Ancient Stirrings",
    "Angel of Sanctions",
    "Anger of the Gods",
    "Anguished Unmaking",
    "Animate Dead",
    "Anje's Ravager",
    "Ankh of Mishra",
    "Annul",
    "Anointer Priest",
    "Anthem of Champions",
    "Anticipate",
    "Antiquities on the Loose",
    "Apex Devastator",
    "Apex Hawks",
    "Aquastrand Spider",
    "Aqueous Form",
    "Arbor Colossus",
    "Arbor Elf",
    "Arc Lightning",
    "Arc Trail",
    "Arcane Signet",
    "Arcbound Bruiser",
    "Arcbound Hybrid",
    "Arcbound Ravager",
    "Arcbound Slith",
    "Arcbound Stinger",
    "Arcbound Worker",
    "Archangel of Thune",
    "Archangel of Tithes",
    "Archdruid's Charm",
    "Archfiend of Ifnir",
    "Architects of Will",
    "Archive Trap",
    "Archmage's Charm",
    "Archon of Emeria",
    "Archon of Justice",
    "Arclight Phoenix",
    "Ardent Plea",
    "Aria of Flame",
    "Arid Mesa",
    "Arrogant Wurm",
    "Artful Dodge",
    "Ashiok, Nightmare Weaver",
    "Ashnod's Altar",
    "Assassin's Trophy",
    "Assault // Battery",
    "Assault Strobe",
    "Attended Knight",
    "Atzocan Archer",
    "Augur of Bolas",
    "Augury Owl",
    "Aura Shards",
    "Aura of Silence",
    "Auriok Champion",
    "Austere Command",
    "Avacyn's Pilgrim",
    "Avatar of the Resolute",
    "Aven Initiate",
    "Aven Mindcensor",
    "Aven Riftwatcher",
    "Aven Squire",
    "Avenger of Zendikar",
    "Awaken the Honored Dead",
    "Axebane Stag",
    "Azorius Signet",
    "Azusa, Lost but Seeking",
    "Back to Basics",
    "Baird, Steward of Argive",
    "Baithook Angler",
    "Balefire Dragon",
    "Baleful Mastery",
    "Baleful Strix",
    "Baloth Prime",
    "Banefire",
    "Banisher Priest",
    "Banishing Light",
    "Bannerhide Krushok",
    "Baral, Chief of Compliance",
    "Barbed Lightning",
    "Barkchannel Pathway",
    "Bartizan Bats",
    "Basalt Monolith",
    "Basilica Screecher",
    "Basilica Stalker",
    "Basking Broodscale",
    "Basking Rootwalla",
    "Bastion of Remembrance",
    "Batterskull",
    "Beacon of Destruction",
    "Beacon of Immortality",
    "Beast Within",
    "Beastmaster Ascension",
    "Bedevil",
    "Bedlam Reveler",
    "Beetleback Chief",
    "Befuddle",
    "Belligerent Sliver",
    "Bellowing Tanglewurm",
    "Beloved Beggar",
    "Benalish Hero",
    "Benthic Biomancer",
    "Biblioplex Tomekeeper",
    "Big Game Hunter",
    "Big Score",
    "Biorhythm",
    "Birds of Paradise",
    "Birgi, God of Storytelling",
    "Birthing Pod",
    "Bitterbloom Bearer",
    "Black Knight",
    "Black Sun's Zenith",
    "Blade Instructor",
    "Blade of the Sixth Pride",
    "Blasphemous Act",
    "Blasphemous Edict",
    "Blazemire Verge",
    "Blazing Firesinger",
    "Blazing Rootwalla",
    "Bleachbone Verge",
    "Blightsteel Colossus",
    "Blinking Spirit",
    "Blinkmoth Nexus",
    "Blood Artist",
    "Blood Moon",
    "Blood Seeker",
    "Bloodbraid Challenger",
    "Bloodbraid Elf",
    "Bloodchief's Thirst",
    "Bloodcrazed Neonate",
    "Bloodfray Giant",
    "Bloodghast",
    "Bloodgift Demon",
    "Bloodhusk Ritualist",
    "Bloodlust Inciter",
    "Bloodrage Brawler",
    "Bloodrock Cyclops",
    "Bloodstained Mire",
    "Bloodthrone Vampire",
    "Bloodtithe Harvester",
    "Blossoming Defense",
    "Blue Elemental Blast",
    "Blur Sliver",
    "Blustersquall",
    "Bog Imp",
    "Bogardan Hellkite",
    "Boggart Brute",
    "Boggart Harbinger",
    "Bola Slinger",
    "Bolrac-Clan Basher",
    "Bomat Courier",
    "Bond of Discipline",
    "Bone Saw",
    "Bone Shards",
    "Bone Shredder",
    "Bone Splinters",
    "Bonescythe Sliver",
    "Bonesplitter Sliver",
    "Bonfire of the Damned",
    "Bontu's Monument",
    "Boom // Bust",
    "Boomerang",
    "Borderland Marauder",
    "Borderland Ranger",
    "Boreal Druid",
    "Boros Charm",
    "Boros Elite",
    "Boros Recruit",
    "Boros Signet",
    "Borrowed Knowledge",
    "Boseiju, Who Endures",
    "Bottle Gnomes",
    "Bottomless Pool // Locker Room",
    "Bountiful Landscape",
    "Brain Maggot",
    "Brainstorm",
    "Branchloft Pathway",
    "Brazen Scourge",
    "Brightclimb Pathway",
    "Brightglass Gearhulk",
    "Brimaz, King of Oreskos",
    "Brindle Boar",
    "Bristly Bill, Spine Sower",
    "Broodspinner",
    "Broodstar",
    "Browbeat",
    "Brush Off",
    "Brute Force",
    "Bruvac the Grandiloquent",
    "Bubble Smuggler",
    "Built to Smash",
    "Bump in the Night",
    "Burgeoning",
    "Burning Inquiry",
    "Burrenton Bombardier",
    "Burrenton Forge-Tender",
    "Butcher of Malakir",
    "Bygone Bishop",
    "Cabal Coffers",
    "Cabal Ritual",
    "Cackling Counterpart",
    "Call of the Herd",
    "Callous Sell-Sword",
    "Cam and Farrik, Havoc Duo",
    "Cancel",
    "Candelabra of Tawnos",
    "Cankerbloom",
    "Canyon Minotaur",
    "Canyon Slough",
    "Captain of the Watch",
    "Captivating Vampire",
    "Carapace Forger",
    "Careful Study",
    "Carnage Interpreter",
    "Carnage Tyrant",
    "Carrier Thrall",
    "Carrion Feeder",
    "Cast Down",
    "Cast Out",
    "Catalog",
    "Catapult Master",
    "Cathar Commando",
    "Cathodion",
    "Cautery Sliver",
    "Celestial Purge",
    "Cemetery Reaper",
    "Cenote Scout",
    "Censor",
    "Centaur Courser",
    "Chain Lightning",
    "Chainer's Edict",
    "Chalice of the Void",
    "Champion of Wits",
    "Champion of the Parish",
    "Champion of the Perished",
    "Chance Encounter",
    "Chandra's Pyrohelix",
    "Chandra, Torch of Defiance",
    "Channel",
    "Chaos Warp",
    "Charging Badger",
    "Charging Monstrosaur",
    "Charging Rhino",
    "Chasm Skulker",
    "Cheerful Osteomancer",
    "Chemister's Insight",
    "Chief of the Foundry",
    "Child of Night",
    "Chord of Calling",
    "Chromatic Lantern",
    "Chromatic Sphere",
    "Chromatic Star",
    "Chrome Mox",
    "Chronatog",
    "Circle of Protection: Black",
    "Circle of Protection: Blue",
    "Circle of Protection: Green",
    "Circle of Protection: Red",
    "Circle of Protection: White",
    "Circuitous Route",
    "Citadel Castellan",
    "Citanul Woodreaders",
    "City of Brass",
    "Civic Wayfinder",
    "Claustrophobia",
    "Clearwater Pathway",
    "Cleaving Sliver",
    "Cling to Dust",
    "Clone",
    "Clot Sliver",
    "Cloud of Faeries",
    "Cloudblazer",
    "Cloudgoat Ranger",
    "Cloudkin Seer",
    "Cloudpost",
    "Cloudreader Sphinx",
    "Cloudshredder Sliver",
    "Coalition Relic",
    "Coastal Piracy",
    "Coiling Oracle",
    "Coldsteel Heart",
    "Collected Company",
    "Collective Brutality",
    "Collective Restraint",
    "Collector Ouphe",
    "Colossal Dreadmaw",
    "Colossus Hammer",
    "Colossus of the Blood Age",
    "Comeuppance",
    "Comforting Counsel",
    "Command Tower",
    "Commander's Sphere",
    "Commercial District",
    "Commune with Nature",
    "Concealing Curtains",
    "Concentrate",
    "Conciliator's Duelist",
    "Conclave Sledge-Captain",
    "Condemn",
    "Cone of Flame",
    "Conflagrate",
    "Consecrated Sphinx",
    "Consider",
    "Consign // Oblivion",
    "Consign to Memory",
    "Consul's Lieutenant",
    "Consult the Star Charts",
    "Consuming Aberration",
    "Contagion Clasp",
    "Containment Construct",
    "Containment Priest",
    "Convolute",
    "Coral Barrier",
    "Coral Eel",
    "Coral Merfolk",
    "Cordial Vampire",
    "Corpse Dance",
    "Corrupt",
    "Cosmogoyf",
    "Cost of Brilliance",
    "Costly Plunder",
    "Counterspell",
    "Courser of Kruphix",
    "Court Homunculus",
    "Court of Cunning",
    "Coveted Jewel",
    "Cower in Fear",
    "Crabomination",
    "Crackling Drake",
    "Cragcrown Pathway",
    "Cranial Plating",
    "Crash Through",
    "Crashing Footfalls",
    "Craw Wurm",
    "Creeping Chill",
    "Cremate",
    "Crested Craghorn",
    "Crimson Wisps",
    "Crippling Blight",
    "Crowd-Control Warden",
    "Crucible of Worlds",
    "Cruel Celebrant",
    "Cruel Somnophage",
    "Crumble to Dust",
    "Crush",
    "Crush of Tentacles",
    "Crypt Incursion",
    "Crypt Sliver",
    "Cryptbreaker",
    "Cryptic Command",
    "Cryptolith Rite",
    "Crystalline Crawler",
    "Crystalline Sliver",
    "Cuboid Colony",
    "Cultivate",
    "Culvert Ambusher",
    "Cunning Sparkmage",
    "Curator of Mysteries",
    "Curiosity",
    "Cursecatcher",
    "Cursed Totem",
    "Cut // Ribbons",
    "Cut Down",
    "Cyclonic Rift",
    "Cytoplast Root-Kin",
    "Dakkon, Shadow Slayer",
    "Damnation",
    "Damping Matrix",
    "Damping Sphere",
    "Dandân",
    "Dark Banishing",
    "Dark Confidant",
    "Dark Prophecy",
    "Dark Ritual",
    "Darkblast",
    "Darkmoss Bridge",
    "Darksteel Axe",
    "Darksteel Colossus",
    "Darksteel Plate",
    "Daru Lancer",
    "Daru Warchief",
    "Dauthi Slayer",
    "Dauthi Voidwalker",
    "Day of Judgment",
    "Day's Undoing",
    "Daze",
    "Dead // Gone",
    "Deadeye Navigator",
    "Deadly Dispute",
    "Deadly Recluse",
    "Death's Shadow",
    "Death's-Head Buzzard",
    "Death-Greeter's Champion",
    "Decree of Justice",
    "Deep Analysis",
    "Deep-Cavern Bat",
    "Defenestrated Phantom",
    "Defiant Khenra",
    "Deflecting Swat",
    "Dehydration",
    "Delighted Halfling",
    "Delver of Secrets",
    "Demonic Consultation",
    "Demonic Tutor",
    "Demystify",
    "Den of the Bugbear",
    "Descendant of Storms",
    "Desert Cerodon",
    "Despark",
    "Desperate Ritual",
    "Despise",
    "Detective's Phoenix",
    "Devoted Druid",
    "Devoted Hero",
    "Diabolic Edict",
    "Diabolic Tutor",
    "Diary of Dreams",
    "Dictate of Erebos",
    "Dictate of the Twin Gods",
    "Diffusion Sliver",
    "Dig Site Inventory",
    "Dimir Signet",
    "Dina's Guidance",
    "Disenchant",
    "Disentomb",
    "Disfigure",
    "Disintegrate",
    "Dismember",
    "Disowned Ancestor",
    "Dispel",
    "Disrupt Decorum",
    "Disrupting Scepter",
    "Dissection Practice",
    "Dissolve",
    "Distortion Strike",
    "Distress",
    "Divination",
    "Doom Blade",
    "Doomed Dissenter",
    "Doomsday Excruciator",
    "Dormant Sliver",
    "Dovin's Veto",
    "Dragon Fodder",
    "Dragon's Eye Sentry",
    "Dragon's Rage Channeler",
    "Dragonback Assault",
    "Dragonlord's Servant",
    "Dragonmaster Outcast",
    "Dramatic Reversal",
    "Drana, Liberator of Malakir",
    "Drannith Healer",
    "Drannith Stinger",
    "Dread Return",
    "Dread Wanderer",
    "Dreadbore",
    "Dreadhorde Arcanist",
    "Dreamstealer",
    "Dreamstone Hedron",
    "Drossforge Bridge",
    "Drown in Ichor",
    "Drown in the Loch",
    "Drowned Secrets",
    "Dryad of the Ilysian Grove",
    "Duplicant",
    "Dusk Legion Zealot",
    "Dwynen, Gilt-Leaf Daen",
    "Eager Cadet",
    "Earthquake",
    "Earthshaker Khenra",
    "Echoing Truth",
    "Eidolon of Rhetoric",
    "Eiganjo, Seat of the Empire",
    "Elder Gargaroth",
    "Eldrazi Confluence",
    "Eldrazi Repurposer",
    "Eldrazi Temple",
    "Electrickery",
    "Electrolyze",
    "Elegant Parlor",
    "Elesh Norn, Grand Cenobite",
    "Elite Interceptor",
    "Elite Spellbinder",
    "Elite Vanguard",
    "Elves of Deep Shadow",
    "Elvish Archdruid",
    "Elvish Archers",
    "Elvish Champion",
    "Elvish Mystic",
    "Elvish Piper",
    "Elvish Reclaimer",
    "Elvish Warrior",
    "Ember Hauler",
    "Ember Swallower",
    "Embereth Shieldbreaker",
    "Embrace the Paradox",
    "Emeria Angel",
    "Emeritus of Abundance",
    "Emeritus of Conflict",
    "Emeritus of Truce",
    "Emeritus of Woe",
    "Emil, Vastlands Roamer",
    "Emperor's Vanguard",
    "Empty the Warrens",
    "Empyrean Eagle",
    "Emrakul, the Aeons Torn",
    "Encouraging Aviator",
    "End of the Hunt",
    "Endless One",
    "Endurance",
    "Enduring Innocence",
    "Enduring Vitality",
    "Enlightened Tutor",
    "Enlisted Wurm",
    "Ensnaring Bridge",
    "Eon Hub",
    "Ephemerate",
    "Epic Confrontation",
    "Erode",
    "Esika's Chariot",
    "Esper Sentinel",
    "Essence Scatter",
    "Essence Warden",
    "Etali, Primal Storm",
    "Eternal Student",
    "Eternal Witness",
    "Ethereal Armor",
    "Evacuation",
    "Everflowing Chalice",
    "Evolving Wilds",
    "Exalted Angel",
    "Exclude",
    "Executioner's Capsule",
    "Exhibition Tidecaller",
    "Exotic Orchard",
    "Expedition Map",
    "Experiment Twelve",
    "Explore",
    "Explosive Vegetation",
    "Expressive Firedancer",
    "Expressive Iteration",
    "Exquisite Firecraft",
    "Eye of Ugin",
    "Fable of the Mirror-Breaker",
    "Fact or Fiction",
    "Fading Hope",
    "Faerie Miscreant",
    "Faerie Snoop",
    "Faerie Vandal",
    "Fairgrounds Warden",
    "Faithless Salvaging",
    "Falkenrath Noble",
    "Fallen Shinobi",
    "Fanatic of Mogis",
    "Fanatic of Xenagos",
    "Fanatical Firebrand",
    "Fangkeeper's Familiar",
    "Far // Away",
    "Farhaven Elf",
    "Farseek",
    "Fatal Push",
    "Fauna Shaman",
    "Felidar Retreat",
    "Felidar Sovereign",
    "Fell",
    "Fellwar Stone",
    "Fertilid",
    "Fervor",
    "Festering Mummy",
    "Fetid Pools",
    "Field Marshal",
    "Field of Ruin",
    "Fiend Hunter",
    "Fierce Guardianship",
    "Fiery Confluence",
    "Fiery Impulse",
    "Fiery Islet",
    "Fiery Temper",
    "Filigree Familiar",
    "Final Judgment",
    "Final Reward",
    "Finale of Devastation",
    "Fire // Ice",
    "Fire Ambush",
    "Fire Imp",
    "Fireball",
    "Firebolt",
    "Fireshrieker",
    "First Sliver's Chosen",
    "Flame Javelin",
    "Flame Rift",
    "Flame Slash",
    "Flame Spirit",
    "Flame Sweep",
    "Flame of Anor",
    "Flameblade Adept",
    "Flare of Denial",
    "Flashfreeze",
    "Fleecemane Lion",
    "Fleshbag Marauder",
    "Flickerwisp",
    "Flight",
    "Fling",
    "Flooded Strand",
    "Floodfarm Verge",
    "Flourishing Fox",
    "Flusterstorm",
    "Font of Mythos",
    "Forbidden Alchemy",
    "Force of Negation",
    "Force of Vigor",
    "Force of Will",
    "Foresee",
    "Fork",
    "Forked Lightning",
    "Foundry Street Denizen",
    "Fractured Sanity",
    "Frenzied Arynx",
    "Frenzied Goblin",
    "Frenzy Sliver",
    "Frilled Deathspitter",
    "Frogmite",
    "Frogtosser Banneret",
    "Frontline Devastator",
    "Frost Breath",
    "Frost Lynx",
    "Frost Titan",
    "Fulminator Mage",
    "Fumigate",
    "Furnace Whelp",
    "Furnace of Rath",
    "Fury",
    "Fury Sliver",
    "Gaea's Cradle",
    "Gaea's Skyfolk",
    "Galerider Sliver",
    "Galvanic Blast",
    "Garruk Wildspeaker",
    "Garruk's Packleader",
    "Gatekeeper of Malakir",
    "Gather Specimens",
    "Gather the Townsfolk",
    "Gatstaf Shepherd",
    "Geier Reach Bandit",
    "Geier Reach Sanitarium",
    "Gemhide Sliver",
    "Gempalm Incinerator",
    "Generous Ent",
    "Generous Gift",
    "Gerrard's Wisdom",
    "Get Lost",
    "Geth's Verdict",
    "Geyadrone Dihada",
    "Ghor-Clan Rampager",
    "Ghost Quarter",
    "Ghost Vacuum",
    "Ghostly Prison",
    "Ghosts of the Innocent",
    "Giant Growth",
    "Giant Spider",
    "Gideon's Reproach",
    "Gift of Orzhova",
    "Gilded Goose",
    "Gilded Lotus",
    "Gingerbrute",
    "Gisela, Blade of Goldnight",
    "Give // Take",
    "Giver of Runes",
    "Gladecover Scout",
    "Glaring Fleshraker",
    "Glen Elendra Archmage",
    "Glimmerpost",
    "Glimpse the Unthinkable",
    "Glint-Nest Crane",
    "Glissa Sunslayer",
    "Glistener Elf",
    "Gloomlake Verge",
    "Glorious Anthem",
    "Glory-Bound Initiate",
    "Gnarled Scarhide",
    "Gnarlid Pack",
    "Gnarlwood Dryad",
    "Go for the Throat",
    "Goblin Arsonist",
    "Goblin Balloon Brigade",
    "Goblin Banneret",
    "Goblin Bombardment",
    "Goblin Bushwhacker",
    "Goblin Chainwhirler",
    "Goblin Chariot",
    "Goblin Chieftain",
    "Goblin Cratermaker",
    "Goblin Electromancer",
    "Goblin Fireslinger",
    "Goblin Gang Leader",
    "Goblin Glasswright",
    "Goblin Grenade",
    "Goblin Guide",
    "Goblin Instigator",
    "Goblin King",
    "Goblin Lackey",
    "Goblin Matron",
    "Goblin Motivator",
    "Goblin Piker",
    "Goblin Piledriver",
    "Goblin Rabblemaster",
    "Goblin Roughrider",
    "Goblin Sledder",
    "Goblin Surprise",
    "Goblin Trashmaster",
    "Goblin War Drums",
    "Goblin War Strike",
    "Goblin Warchief",
    "Goblin Wardriver",
    "Goldmire Bridge",
    "Goldnight Commander",
    "Goldspan Dragon",
    "Golgari Brownscale",
    "Golgari Grave-Troll",
    "Golgari Signet",
    "Golgari Thug",
    "Golos, Tireless Pilgrim",
    "Gonti, Lord of Luxury",
    "Gorehorn Minotaurs",
    "Gorilla Chieftain",
    "Grab the Reins",
    "Grafdigger's Cage",
    "Granite Witness",
    "Grapeshot",
    "Grapple with the Past",
    "Grasp of Darkness",
    "Grave Pact",
    "Gravecrawler",
    "Gray Ogre",
    "Grazing Whiptail",
    "Greasewrench Goblin",
    "Great Hall of the Biblioplex",
    "Greater Basilisk",
    "Greater Good",
    "Greater Sandwurm",
    "Green Sun's Zenith",
    "Greenbelt Radical",
    "Greenweaver Druid",
    "Greenwheel Liberator",
    "Grief",
    "Grim Affliction",
    "Grim Flayer",
    "Grim Lavamancer",
    "Grim Monolith",
    "Griselbrand",
    "Grisly Salvage",
    "Grizzled Outrider",
    "Grizzly Bears",
    "Groundbreaker",
    "Groundshaker Sliver",
    "Groundswell",
    "Group Project",
    "Growing Ranks",
    "Growing Rites of Itlimoc",
    "Gruul Signet",
    "Guardian Idol",
    "Guardian Scalelord",
    "Guide of Souls",
    "Gush",
    "Hamlet Glutton",
    "Hammer Dropper",
    "Hammerhand",
    "Hands of Binding",
    "Hangarback Walker",
    "Hanweir Garrison",
    "Hanweir Lancer",
    "Harbinger of the Seas",
    "Harmonic Sliver",
    "Harmonize",
    "Harmonized Trio",
    "Harrow",
    "Harsh Annotation",
    "Hauntwoods Shrieker",
    "Haywire Mite",
    "Healer's Hawk",
    "Healing Salve",
    "Heart Sliver",
    "Heart of Kiran",
    "Heartfire Immolator",
    "Heartless Act",
    "Heated Argument",
    "Hedge Maze",
    "Hedron Archive",
    "Hedron Crab",
    "Heliod's Pilgrim",
    "Heliod, Sun-Crowned",
    "Helium Squirter",
    "Hellrider",
    "Helm of the Host",
    "Hengegate Pathway",
    "Hero of Oxid Ridge",
    "Hero's Downfall",
    "Heroic Intervention",
    "Hibernation Sliver",
    "Hidden Herbalists",
    "Hidden Strings",
    "Hide in Plain Sight",
    "Hieroglyphic Illumination",
    "Highborn Ghoul",
    "Hijack",
    "Hill Giant",
    "Hinterland Hermit",
    "History of Benalia",
    "Hollow One",
    "Holy Light",
    "Holy Strength",
    "Honorbound Page",
    "Honored Hydra",
    "Hooded Brawler",
    "Hordeling Outburst",
    "Horizon Canopy",
    "Horizon Spellbomb",
    "Horned Sliver",
    "Horned Turtle",
    "Hornet Queen",
    "Hornet Sting",
    "Horror of the Broken Lands",
    "Hostage Taker",
    "Howl from Beyond",
    "Howling Mine",
    "Hundred-Talon Kami",
    "Hungry Graffalon",
    "Hunter Sliver",
    "Hurloon Minotaur",
    "Hushbringer",
    "Hushwood Verge",
    "Hydro-Channeler",
    "Hydroblast",
    "Hymn to Tourach",
    "Hypnotic Specter",
    "Icatian Javelineers",
    "Icetill Explorer",
    "Ichor Wellspring",
    "Ichorid",
    "Icy Manipulator",
    "Ignoble Hierarch",
    "Ill-Tempered Cyclops",
    "Immaculate Magistrate",
    "Impassioned Orator",
    "Imperial Recruiter",
    "Imperial Seal",
    "Imposing Vantasaur",
    "Impractical Joke",
    "Impulse",
    "Incinerate",
    "Indrik Stomphowler",
    "Indulgent Aristocrat",
    "Indulgent Tormentor",
    "Inexorable Tide",
    "Infernal Grasp",
    "Infirmary Healer",
    "Inkmoth Nexus",
    "Innocent Blood",
    "Inquisition of Kozilek",
    "Inquisitive Puppet",
    "Inside Out",
    "Inspiration",
    "Inspired Charge",
    "Intervention Pact",
    "Into the Roil",
    "Inventor's Apprentice",
    "Invisible Stalker",
    "Irrigated Farmland",
    "Isochron Scepter",
    "Isolate",
    "It That Heralds the End",
    "Izzet Charm",
    "Izzet Signet",
    "Jace Beleren",
    "Jace's Ingenuity",
    "Jace's Phantasm",
    "Jace, Wielder of Mysteries",
    "Jace, the Mind Sculptor",
    "Jadelight Ranger",
    "Jadzi, Steward of Fate",
    "Jaya's Greeting",
    "Jeska's Will",
    "Jin-Gitaxias, Core Augur",
    "Joined Researchers",
    "Joraga Warcaller",
    "Jori En, Ruin Diver",
    "Journey to Nowhere",
    "Juggernaut",
    "Junk Diver",
    "Juzám Djinn",
    "Kaldra Compleat",
    "Kappa Cannoneer",
    "Kari Zev, Skyship Raider",
    "Karn Liberated",
    "Karn's Bastion",
    "Karn, Scion of Urza",
    "Keen Sense",
    "Keen-Eyed Curator",
    "Kessig Prowler",
    "Kessig Wolf Run",
    "Kestia, the Cultivator",
    "Khenra Eternal",
    "Killian's Confidence",
    "Kiln Fiend",
    "Kingpin's Pet",
    "Kinjalli's Caller",
    "Kinsbaile Cavalier",
    "Kird Ape",
    "Kirol, History Buff",
    "Kitchen Finks",
    "Kite Shield",
    "Kitesail Freebooter",
    "Knight Errant",
    "Knight Exemplar",
    "Knight of Autumn",
    "Knight of Meadowgrain",
    "Knight of the Ebon Legion",
    "Knight of the Pilgrim's Road",
    "Knight of the Reliquary",
    "Knight of the White Orchid",
    "Kodama of the West Tree",
    "Kodama's Reach",
    "Kokusho, the Evening Star",
    "Kolaghan's Command",
    "Koma, Cosmos Serpent",
    "Kor Firewalker",
    "Kor Hookmaster",
    "Kor Sanctifiers",
    "Kor Skyfisher",
    "Korvold, Fae-Cursed King",
    "Kozilek's Command",
    "Kozilek's Predator",
    "Krark-Clan Ironworks",
    "Krenko's Command",
    "Krenko, Mob Boss",
    "Kroxa, Titan of Death's Hunger",
    "Kruin Outlaw",
    "Laboratory Maniac",
    "Lambholt Elder",
    "Landscape Painter",
    "Languish",
    "Lash Out",
    "Last Gasp",
    "Last Thoughts",
    "Lava Axe",
    "Lava Coil",
    "Lavabelly Sliver",
    "Lay Down Arms",
    "Lay of the Land",
    "Lead the Stampede",
    "Leech Collector",
    "Leeching Sliver",
    "Legion Extruder",
    "Legion Lieutenant",
    "Legion Loyalist",
    "Legion Warboss",
    "Legion's Landing",
    "Leonin Arbiter",
    "Leonin Relic-Warder",
    "Leonin Skyhunter",
    "Leonin Warleader",
    "Leyline Binding",
    "Leyline of the Guildpact",
    "Leyline of the Void",
    "Life from the Loam",
    "Lightkeeper of Emeria",
    "Lightning Bolt",
    "Lightning Elemental",
    "Lightning Greaves",
    "Lightning Helix",
    "Lightning Mauler",
    "Lightning Skelemental",
    "Lightning Strike",
    "Liliana of the Veil",
    "Liliana's Mastery",
    "Liliana's Specter",
    "Liliana, the Last Hope",
    "Lingering Souls",
    "Lion Sash",
    "Living End",
    "Llanowar Elves",
    "Llanowar Loamspeaker",
    "Llanowar Tribe",
    "Llanowar Visionary",
    "Loam Lion",
    "Lodestone Golem",
    "Lonis, Genetics Expert",
    "Looming Shade",
    "Loot, the Pathfinder",
    "Loran of the Third Path",
    "Lord of the Accursed",
    "Lord of the Undead",
    "Lotus Field",
    "Loxodon Hierarch",
    "Loxodon Warhammer",
    "Luminarch Ascension",
    "Lumra, Bellow of the Woods",
    "Lunarch Veteran",
    "Lure",
    "Lush Portico",
    "Lymph Sliver",
    "Mad Ratter",
    "Madcap Experiment",
    "Maddening Cacophony",
    "Maelstrom Archangel",
    "Maelstrom Artisan",
    "Maelstrom Nexus",
    "Maelstrom Pulse",
    "Magda, Brazen Outlaw",
    "Magma Jet",
    "Magma Spray",
    "Magus of the Mirror",
    "Magus of the Moon",
    "Mahamoti Djinn",
    "Mai, Scornful Striker",
    "Make Disappear",
    "Malakir Bloodwitch",
    "Malevolent Rumble",
    "Man-o'-War",
    "Mana Clash",
    "Mana Confluence",
    "Mana Crypt",
    "Mana Drain",
    "Mana Leak",
    "Mana Reflection",
    "Mana Tithe",
    "Mana Vault",
    "Manaweft Sliver",
    "Manic Vandal",
    "Marauding Blight-Priest",
    "Marauding Mako",
    "Mardu Hateblade",
    "Mark of Mutiny",
    "Mark of the Vampire",
    "Marsh Casualties",
    "Marsh Flats",
    "Marsh Viper",
    "Mask of Memory",
    "Master of Cruelties",
    "Master of Death",
    "Master of the Pearl Trident",
    "Mathemagics",
    "Matterbending Mage",
    "Mausoleum Turnkey",
    "Mausoleum Wanderer",
    "Mayhem Devil",
    "Mayor of Avabruck",
    "Maze of Ith",
    "Meat Locker // Drowned Diner",
    "Megantic Sliver",
    "Megrim",
    "Memory Deluge",
    "Mending Hands",
    "Mental Note",
    "Mer-Ek Nightblade",
    "Merfolk Branchwalker",
    "Merfolk Looter",
    "Merfolk Mistbinder",
    "Merfolk Skydiver",
    "Merfolk Thaumaturgist",
    "Merfolk of the Pearl Trident",
    "Merrow Reejerey",
    "Mesa Pegasus",
    "Mesmeric Orb",
    "Messenger Falcons",
    "Metamorphosis Fanatic",
    "Midnight Haunting",
    "Midnight Reaper",
    "Midnight Recovery",
    "Might Sliver",
    "Mightform Harmonizer",
    "Millstone",
    "Mind Bend",
    "Mind Roots",
    "Mind Rot",
    "Mind Spring",
    "Mind Stone",
    "Mind Twist",
    "Mind into Matter",
    "Mind's Desire",
    "Ministrant of Obligation",
    "Mirror Image",
    "Mirror Universe",
    "Mirrorform",
    "Miscalculation",
    "Mishra's Factory",
    "Mist Raven",
    "Mistcutter Hydra",
    "Mistral Charger",
    "Mistral Singer",
    "Mistvault Bridge",
    "Misty Rainforest",
    "Mizzium Mortars",
    "Moan of the Unhallowed",
    "Mockingbird",
    "Mogg Fanatic",
    "Mogg Raider",
    "Molten-Core Maestro",
    "Moment of Reckoning",
    "Moment's Peace",
    "Monastery Swiftspear",
    "Mondronen Shaman",
    "Mons's Goblin Raiders",
    "Monstrous Carabid",
    "Monument to Endurance",
    "Moonshadow",
    "Morbid Opportunist",
    "Mortify",
    "Mortuary Mire",
    "Mosquito Guard",
    "Mossborn Hydra",
    "Mosswort Bridge",
    "Mountain Goat",
    "Mourning Patrol",
    "Mourning Thrull",
    "Mouth // Feed",
    "Mox Amber",
    "Mox Diamond",
    "Mox Opal",
    "Muldrotha, the Gravetide",
    "Mulldrifter",
    "Munitions Expert",
    "Murder",
    "Murderous Cut",
    "Murderous Redcap",
    "Murktide Regent",
    "Muscle Sliver",
    "Muse Seeker",
    "Museum Nightwatch",
    "Mutable Explorer",
    "Mutagenic Growth",
    "Mutated Cultist",
    "Mutavault",
    "Myr Battlesphere",
    "Myr Enforcer",
    "Myr Retriever",
    "Mystic Forge",
    "Mystic Remora",
    "Mystic Snake",
    "Mystical Dispute",
    "Mystical Tutor",
    "Naga Vitalist",
    "Nantuko Husk",
    "Narcomoeba",
    "Narnam Renegade",
    "Narset, Parter of Veils",
    "Naturalize",
    "Nature's Claim",
    "Nature's Lore",
    "Nearheath Pilgrim",
    "Necrotic Ooze",
    "Necrotic Sliver",
    "Needleverge Pathway",
    "Negate",
    "Nekrataal",
    "Nervous Gardener",
    "Nessian Asp",
    "Nessian Demolok",
    "Nessian Wilds Ravager",
    "Nest Invader",
    "Nettlecyst",
    "Night's Whisper",
    "Nightshade Peddler",
    "Nihil Spellbomb",
    "Nimble Mongoose",
    "Nimble-Blade Khenra",
    "Niv-Mizzet, Parun",
    "Noble Hierarch",
    "Nowhere to Run",
    "Noxious Gearhulk",
    "Null Rod",
    "Nulldrifter",
    "Nurturing Peatland",
    "Obelisk of Urd",
    "Oblivion Ring",
    "Oblivion Stone",
    "Obsianus Golem",
    "Obstinate Baloth",
    "Ocelot Pride",
    "Offender at Large",
    "Ohran Frostfang",
    "Oketra's Attendant",
    "Oko, Thief of Crowns",
    "Oliphaunt",
    "Omen of the Sea",
    "Ominous Harvest",
    "Omnath, Locus of Creation",
    "Omnath, Locus of Rage",
    "Omniscience",
    "Onakke Ogre",
    "Onward // Victory",
    "Opaline Sliver",
    "Open Fire",
    "Open the Vaults",
    "Ophidian",
    "Ophidian Eye",
    "Ophiomancer",
    "Opportunity",
    "Opposition",
    "Opt",
    "Oracle of Bones",
    "Oracle of Mul Daya",
    "Orcish Bowmasters",
    "Ornithopter",
    "Ornithopter of Paradise",
    "Orysa, Tide Choreographer",
    "Orzhov Signet",
    "Otawara, Soaring City",
    "Otepec Huntmaster",
    "Ouroboroid",
    "Oust",
    "Outland Liberator",
    "Overlord of the Balemurk",
    "Overlord of the Boilerbilges",
    "Overlord of the Floodpits",
    "Overlord of the Hauntwoods",
    "Overlord of the Mistmoors",
    "Overwhelming Stampede",
    "Owlin Historian",
    "Pack Rat",
    "Pact of Negation",
    "Pact of the Titan",
    "Painful Truths",
    "Palace Sentinels",
    "Palisade Giant",
    "Panther Warriors",
    "Paradise Mantle",
    "Paradoxical Outcome",
    "Parallax Dementia",
    "Parallax Nexus",
    "Parallax Tide",
    "Paranoid Delusions",
    "Part the Waterveil",
    "Patchwork Automaton",
    "Path of Discovery",
    "Path of Peace",
    "Path to Exile",
    "Pearled Unicorn",
    "Peer Through Depths",
    "Pelakka Wurm",
    "Pelt Collector",
    "Pensive Professor",
    "Pentad Prism",
    "Penumbra Spider",
    "Penumbra Wurm",
    "Pernicious Deed",
    "Pestbrood Sloth",
    "Pestermite",
    "Pestilence",
    "Phantasmal Bear",
    "Phantasmal Image",
    "Phantom Monster",
    "Phantom Warrior",
    "Pharagax Giant",
    "Phelia, Exuberant Shepherd",
    "Pheres-Band Centaurs",
    "Phlage, Titan of Fire's Fury",
    "Phyrexian Altar",
    "Phyrexian Arena",
    "Phyrexian Crusader",
    "Phyrexian Gargantua",
    "Phyrexian Metamorph",
    "Phyrexian Reclamation",
    "Phyrexian Revoker",
    "Phyrexian Scriptures",
    "Phyrexian Soulgorger",
    "Pia Nalaar",
    "Pia and Kiran Nalaar",
    "Pigment Wrangler",
    "Pilgrim's Eye",
    "Pillarfield Ox",
    "Pinnacle Emissary",
    "Pithing Needle",
    "Plague Wind",
    "Plagued Rusalka",
    "Planar Cleansing",
    "Planar Nexus",
    "Plated Crusher",
    "Plated Sliver",
    "Platinum Emperion",
    "Plaxcaster Frogling",
    "Plummet",
    "Poisoner's Apprentice",
    "Polluted Delta",
    "Pongify",
    "Portable Hole",
    "Portal to Phyrexia",
    "Postmortem Professor",
    "Potioner's Trove",
    "Pounce",
    "Pouncing Cheetah",
    "Power Depot",
    "Power Word Kill",
    "Pox Plague",
    "Preacher of the Schism",
    "Precognitive Perception",
    "Predatory Sliver",
    "Preordain",
    "Pressure Point",
    "Prey Upon",
    "Pridemalkin",
    "Priest of Fell Rites",
    "Priest of Titania",
    "Prismatic Lens",
    "Prized Amalgam",
    "Prodigal Sorcerer",
    "Profit // Loss",
    "Proft's Eidetic Memory",
    "Promise of Power",
    "Propaganda",
    "Prophetic Bolt",
    "Proven Combatant",
    "Psychic Corrosion",
    "Pterafractyl",
    "Pteramander",
    "Pull from the Grave",
    "Pulse of Murasa",
    "Pure // Simple",
    "Pursue the Past",
    "Putrefy",
    "Putrefy (Modern)",
    "Pyre Charger",
    "Pyrite Spellbomb",
    "Pyroblast",
    "Pyroclasm",
    "Pyrohemia",
    "Pyrokinesis",
    "Pyrotechnic Performer",
    "Qasali Pridemage",
    "Quandrix Charm",
    "Quandrix Cryptomancer",
    "Quantum Riddler",
    "Quicksilver Amulet",
    "Quill-Blade Laureate",
    "Quilled Sliver",
    "Qumulox",
    "Rabid Bite",
    "Radical Idea",
    "Ragavan, Nimble Pilferer",
    "Raging Goblin",
    "Railway Brawler",
    "Raise Dead",
    "Raise the Alarm",
    "Rakdos Signet",
    "Rakish Scoundrel",
    "Rakshasa's Bargain",
    "Ramos, Dragon Engine",
    "Rampaging Baloths",
    "Rampant Growth",
    "Ramunap Excavator",
    "Rancor",
    "Rancorous Archaic",
    "Ranger of Eos",
    "Ranger-Captain of Eos",
    "Ranging Raptors",
    "Rapid Hybridization",
    "Raptor Hatchling",
    "Rattlechains",
    "Raucous Theater",
    "Raven's Crime",
    "Ravenous Baloth",
    "Ravenous Chupacabra",
    "Ravenous Rats",
    "Razortide Bridge",
    "Read the Bones",
    "Read the Tides",
    "Ready // Willing",
    "Reality Shift",
    "Reality Smasher",
    "Reanimate",
    "Reassembling Skeleton",
    "Reckless Abandon",
    "Reckless Spite",
    "Reckless Waif",
    "Reckless Wurm",
    "Reckoner Bankbuster",
    "Reclaim",
    "Reclamation Sage",
    "Red Elemental Blast",
    "Red Sun's Zenith",
    "Redirect",
    "Rediscover the Way",
    "Redwood Treefolk",
    "Reflecting Pool",
    "Reflector Mage",
    "Reforge the Soul",
    "Regisaur Alpha",
    "Regrowth",
    "Relentless Assault",
    "Reliquary Tower",
    "Remand",
    "Render Speechless",
    "Renegade Tactics",
    "Repay in Kind",
    "Repeal",
    "Reprisal",
    "Repulse",
    "Rest in Peace",
    "Restless Anchorage",
    "Restless Bivouac",
    "Restless Cottage",
    "Restless Fortress",
    "Restless Prairie",
    "Restless Reef",
    "Restless Ridgeline",
    "Restless Spire",
    "Restless Vents",
    "Restless Vinestalk",
    "Restoration Angel",
    "Return to Dust",
    "Reveillark",
    "Reverberate",
    "Rhystic Study",
    "Ribbons of Night",
    "Ridgescale Tusker",
    "Rift Bolt",
    "Riftburst Hellion",
    "Ripjaw Raptor",
    "Rishadan Airship",
    "Rishadan Port",
    "Risk Factor",
    "Rite of Flame",
    "Rite of Replication",
    "Riverglide Pathway",
    "Riverpyre Verge",
    "Roast",
    "Robber of the Rich",
    "Rofellos, Llanowar Emissary",
    "Rogue's Gloves",
    "Roiling Vortex",
    "Ronom Unicorn",
    "Root Manipulation",
    "Rootwater Hunter",
    "Rough // Tumble",
    "Rout",
    "Royal Assassin",
    "Rubblehulk",
    "Rude Awakening",
    "Ruin Crab",
    "Rule of Law",
    "Rumbling Baloth",
    "Run Behind",
    "Rune of Protection: Black",
    "Rune of Protection: Red",
    "Runeclaw Bear",
    "Rustvale Bridge",
    "Sab-Sunen, Luxa Embodied",
    "Sacred Cat",
    "Saheeli Rai",
    "Sakura-Tribe Elder",
    "Sakura-Tribe Scout",
    "Sanar, Unfinished Genius",
    "Sanctifier en-Vec",
    "Sandsteppe Outcast",
    "Savai Thundermane",
    "Savannah Lions",
    "Scab-Clan Mauler",
    "Scalding Tarn",
    "Scapeshift",
    "Scathe Zombies",
    "Scathing Shadelock",
    "Scattered Groves",
    "Scavenging Ooze",
    "Scheming Silvertongue",
    "Scolding Administrator",
    "Scorch Spitter",
    "Scrap Trawler",
    "Scrapheap Scrounger",
    "Scryb Sprites",
    "Scute Swarm",
    "Sea Eagle",
    "Sea Gate Oracle",
    "Seal of Cleansing",
    "Seal of Doom",
    "Seal of Fire",
    "Seal of Primordium",
    "Seal of Removal",
    "Seal of Strength",
    "Search for Azcanta",
    "Searing Blood",
    "Searing Spear",
    "Seasoned Pyromancer",
    "Sedge Troll",
    "Seedborn Muse",
    "Seekers' Squire",
    "Selesnya Signet",
    "Selfless Spirit",
    "Send in the Pest",
    "Sengir Vampire",
    "Sensei's Divining Top",
    "Sentinel Sliver",
    "Sentinel Spider",
    "Sentinel of the Nameless City",
    "Serra Angel",
    "Serra Avenger",
    "Serum Visions",
    "Servant of Tymaret",
    "Servant of the Scale",
    "Servo Exhibition",
    "Settle the Wreckage",
    "Severed Legion",
    "Severed Strands",
    "Shadow Slice",
    "Shadowmage Infiltrator",
    "Shadowspear",
    "Shady Informant",
    "Shardless Agent",
    "Shared Triumph",
    "Shatter",
    "Shefet Monitor",
    "Shelldock Isle",
    "Sheltered Thicket",
    "Sheltering Landscape",
    "Sheoldred's Edict",
    "Sheoldred, Whispering One",
    "Shepherd of Rot",
    "Shield Sphere",
    "Shifting Ceratops",
    "Shifting Woodland",
    "Shiko and Narset, Unified",
    "Shivan Dragon",
    "Shock",
    "Shoreline Ranger",
    "Shorikai, Genesis Engine",
    "Shrapnel Blast",
    "Shriekmaw",
    "Sidewinder Sliver",
    "Siege Rhino",
    "Siege-Gang Commander",
    "Sigarda's Aid",
    "Signal Pest",
    "Silent Clearing",
    "Silhana Ledgewalker",
    "Silverback Ape",
    "Silverblade Paladin",
    "Silverbluff Bridge",
    "Silvergill Adept",
    "Silversmote Ghoul",
    "Simian Sling",
    "Simian Spirit Guide",
    "Simic Ascendancy",
    "Simic Initiate",
    "Simic Signet",
    "Sinew Sliver",
    "Sink into Stupor",
    "Sinkhole",
    "Sinuous Striker",
    "Sip of Hemlock",
    "Sizzle",
    "Skinbrand Goblin",
    "Skinrender",
    "Skirk Marauder",
    "Skirk Prospector",
    "Skitter of Lizards",
    "Skred",
    "Skullclamp",
    "Skullcrack",
    "Skyclave Apparition",
    "Skycoach Conductor",
    "Skycoach Waypoint",
    "Skyhunter Patrol",
    "Skyhunter Skirmisher",
    "Skyknight Legionnaire",
    "Skymarcher Aspirant",
    "Skyraker Giant",
    "Skyshroud Claim",
    "Skyshroud Elite",
    "Slagstorm",
    "Slagwoods Bridge",
    "Slaughter Pact",
    "Slaughterhorn",
    "Sleep",
    "Slip Out the Back",
    "Slither Blade",
    "Sliver Hivelord",
    "Sliver Legion",
    "Smallpox",
    "Smash to Smithereens",
    "Smelt",
    "Smite the Monstrous",
    "Smoke",
    "Smother",
    "Smothering Tithe",
    "Snake of the Golden Grove",
    "Snakeskin Veil",
    "Snapcaster Mage",
    "Snapping Drake",
    "Sneak Attack",
    "Snuff Out",
    "Sojourner's Companion",
    "Sokenzan, Crucible of Defiance",
    "Sol Ring",
    "Solemn Recruit",
    "Solemn Simulacrum",
    "Solemnity",
    "Soltari Champion",
    "Soltari Monk",
    "Soltari Priest",
    "Somber Hoverguard",
    "Sorin, Grim Nemesis",
    "Soul Conduit",
    "Soul Feast",
    "Soul Snare",
    "Soul Warden",
    "Soul's Attendant",
    "Soul-Guide Lantern",
    "Soul-Scar Mage",
    "Soulherder",
    "Sowing Mycospawn",
    "Spark Double",
    "Specter's Shroud",
    "Spectral Flight",
    "Spectral Procession",
    "Spectral Sailor",
    "Spell Pierce",
    "Spell Queller",
    "Spell Snare",
    "Spellbook",
    "Spellbook Seeker",
    "Spellseeker",
    "Sphere of Resistance",
    "Sphere of Safety",
    "Sphinx of the Steel Wind",
    "Sphinx's Insight",
    "Spidersilk Armor",
    "Spike Feeder",
    "Spikeshot Elder",
    "Spikeshot Goblin",
    "Spiketail Hatchling",
    "Spine of Ish Sah",
    "Spined Wurm",
    "Spinerock Knoll",
    "Spinneret Sliver",
    "Spirit of the Labyrinth",
    "Spiritcall Enthusiast",
    "Spite // Malice",
    "Spiteful Sliver",
    "Splinter Twin",
    "Spoils of the Vault",
    "Sporemound",
    "Spreading Seas",
    "Spring // Mind",
    "Springbloom Druid",
    "Springleaf Parade",
    "Sprite Dragon",
    "Sram, Senior Edificer",
    "Stadium Tidalmage",
    "Staggershock",
    "Stalwart Aven",
    "Stand // Deliver",
    "Standing Troops",
    "Star Compass",
    "Static Prison",
    "Steadfast Sentinel",
    "Steady Progress",
    "Steel Leaf Champion",
    "Steelform Sliver",
    "Stern Scolding",
    "Stillmoon Cavalier",
    "Stinkweed Imp",
    "Stoke the Flames",
    "Stolen Identity",
    "Stone Rain",
    "Stonecoil Serpent",
    "Stony Silence",
    "Stonybrook Banneret",
    "Storm Crow",
    "Stormblood Berserker",
    "Stormbreath Dragon",
    "Stormchaser Mage",
    "Stormfront Pegasus",
    "Strangle",
    "Strangleroot Geist",
    "Strategic Planning",
    "Street Spasm",
    "Street Wraith",
    "Stress Dream",
    "Strider Harness",
    "Striking Sliver",
    "Strip Mine",
    "Strixhaven Skycoach",
    "Stroke of Genius",
    "Stromkirk Captain",
    "Stromkirk Noble",
    "Stromkirk Patrol",
    "Stubborn Denial",
    "Stunt Double",
    "Subtlety",
    "Sudden Edict",
    "Sulfuric Vortex",
    "Summoned Dromedary",
    "Summoner's Pact",
    "Sunbaked Canyon",
    "Sundering Eruption",
    "Sundial of the Infinite",
    "Sunhome Stalwart",
    "Sunlance",
    "Sunscorched Desert",
    "Sunscourge Champion",
    "Suntail Hawk",
    "Supply // Demand",
    "Suppression Field",
    "Supreme Phantom",
    "Supreme Verdict",
    "Surgical Extraction",
    "Suture Priest",
    "Svyelun of Sea and Sky",
    "Swan Song",
    "Sweltering Suns",
    "Swiftfoot Boots",
    "Switcheroo",
    "Sword of Body and Mind",
    "Sword of Feast and Famine",
    "Sword of Fire and Ice",
    "Sword of Light and Shadow",
    "Sword of Truth and Justice",
    "Sword of Vengeance",
    "Sword of War and Peace",
    "Sword of the Meek",
    "Swords to Plowshares",
    "Sylvan Advocate",
    "Sylvan Caryatid",
    "Sylvan Ranger",
    "Sylvan Safekeeper",
    "Sylvan Spellbomb",
    "Syndic of Tithes",
    "Tackle Artist",
    "Tah-Crop Elite",
    "Tah-Crop Skirmisher",
    "Tainted Strike",
    "Takenuma, Abandoned Mire",
    "Tale's End",
    "Talisman of Conviction",
    "Talisman of Creativity",
    "Talisman of Curiosity",
    "Talisman of Hierarchy",
    "Talisman of Impulse",
    "Talisman of Indulgence",
    "Talisman of Resilience",
    "Talisman of Unity",
    "Talon Gates of Madara",
    "Talon Sliver",
    "Tam, Observant Sequencer",
    "Tamiyo, Collector of Tales",
    "Tandem Lookout",
    "Tanglepool Bridge",
    "Tarfire",
    "Tasha's Hideous Laughter",
    "Tasigur, the Golden Fang",
    "Teacher's Pest",
    "Tear Asunder",
    "Teferi's Protection",
    "Teferi, Hero of Dominaria",
    "Teferi, Time Raveler",
    "Telekinetic Sliver",
    "Teleportal",
    "Telling Time",
    "Tempered Sliver",
    "Tempest Angler",
    "Temple Bell",
    "Temporal Mastery",
    "Tempt with Bunnies",
    "Tempt with Glory",
    "Tempt with Reflections",
    "Tempt with Vengeance",
    "Temur Battle Rage",
    "Tendrils of Corruption",
    "Tenured Concocter",
    "Terminate",
    "Terminus",
    "Terra Stomper",
    "Territorial Hammerskull",
    "Territorial Kavu",
    "Terror",
    "Test of Endurance",
    "Tester of the Tangential",
    "Teval, Arbiter of Virtue",
    "Tezzeret, Cruel Captain",
    "Thalia, Guardian of Thraben",
    "Thalia, Heretic Cathar",
    "Thassa's Oracle",
    "The Birth of Meletis",
    "The Dawning Archaic",
    "The Eldest Reborn",
    "The Endstone",
    "The Everflowing Well",
    "The Gitrog Monster",
    "The Great Henge",
    "The Mightstone and Weakstone",
    "The One Ring",
    "Thespian's Stage",
    "Thieving Magpie",
    "Thing in the Ice",
    "Think Twice",
    "Third Path Iconoclast",
    "Thopter Foundry",
    "Thorn of Amethyst",
    "Thorncaster Sliver",
    "Thornglint Bridge",
    "Thornspire Verge",
    "Thornweald Archer",
    "Thought Erasure",
    "Thought Monitor",
    "Thought Reflection",
    "Thought Scour",
    "Thought Vessel",
    "Thoughtseize",
    "Thraben Inspector",
    "Thragtusk",
    "Thran Dynamo",
    "Thrashing Brontodon",
    "Threaten",
    "Three Tree City",
    "Three Visits",
    "Thrill of Possibility",
    "Throne of Geth",
    "Through the Breach",
    "Thrummingbird",
    "Thrun, the Last Troll",
    "Thunder Brute",
    "Thunderdrum Soloist",
    "Thundering Falls",
    "Thundering Giant",
    "Thundertrap Trainer",
    "Tidehollow Sculler",
    "Tideshaper Mystic",
    "Tidings",
    "Time Sieve",
    "Timeless Witness",
    "Tireless Missionaries",
    "Tireless Provisioner",
    "Tireless Tracker",
    "Tishana's Tidebinder",
    "Tishana's Wayfinder",
    "Titan's Strength",
    "Titania, Protector of Argoth",
    "Titanic Growth",
    "Tithe Drinker",
    "Tocatli Honor Guard",
    "Together as One",
    "Toil // Trouble",
    "Tolarian Terror",
    "Tolarian Winds",
    "Tome Scour",
    "Tooth and Nail",
    "Topan Freeblade",
    "Torbran, Thane of Red Fell",
    "Torch Courier",
    "Torch Fiend",
    "Tormented Pariah",
    "Tormented Soul",
    "Tormenting Voice",
    "Torpor Orb",
    "Torsten, Founder of Benalia",
    "Tourach, Dread Cantor",
    "Toxic Deluge",
    "Tragic Slip",
    "Trained Armodon",
    "Trait Doctoring",
    "Traitorous Blood",
    "Tranquility",
    "Traumatize",
    "Trenchpost",
    "Tribal Flames",
    "Trinisphere",
    "Triskelion",
    "Triumph of Gerrard",
    "Triumph of the Hordes",
    "Trumpet Blast",
    "Trusted Forcemage",
    "Trusty Machete",
    "Trygon Predator",
    "Tundra Wolves",
    "Turnabout",
    "Tuskguard Captain",
    "Twisted Abomination",
    "Twisted Image",
    "Twisted Landscape",
    "Two-Headed Sliver",
    "Typhoid Rats",
    "Ulamog, the Ceaseless Hunger",
    "Ulna Alley Shopkeep",
    "Ultimate Price",
    "Ulvenwald Captive",
    "Umezawa's Jitte",
    "Uncaged Fury",
    "Underground Mortuary",
    "Underworld Connections",
    "Underworld Dreams",
    "Unearth",
    "Unholy Annex // Ritual Chamber",
    "Unholy Heat",
    "Unholy Strength",
    "Universal Automaton",
    "Unsummon",
    "Untamed Hunger",
    "Unwavering Initiate",
    "Up the Beanstalk",
    "Upheaval",
    "Ur-Golem's Eye",
    "Urabrask the Hidden",
    "Urborg, Tomb of Yawgmoth",
    "Uro, Titan of Nature's Wrath",
    "Ursine Monstrosity",
    "Urza's Mine",
    "Urza's Power Plant",
    "Urza's Saga",
    "Urza's Tower",
    "Urza, Chief Artificer",
    "Urza, Lord Protector",
    "Valiant Rescuer",
    "Vampire Cutthroat",
    "Vampire Hexmage",
    "Vampire Interloper",
    "Vampire Nighthawk",
    "Vandalblast",
    "Vapor Snag",
    "Vastlands Scavenger",
    "Vastwood Gorger",
    "Vendetta",
    "Venerable Monk",
    "Vengeful Dead",
    "Vengevine",
    "Venom Sliver",
    "Venser's Journal",
    "Verdant Catacombs",
    "Vesuva",
    "Veteran Armorer",
    "Veteran Swordsmith",
    "Vexing Devil",
    "Vexing Shusher",
    "Viashino Pyromancer",
    "Viashino Shanktail",
    "Vibrant Outburst",
    "Vicious Conquistador",
    "Vigean Graftmage",
    "Village Messenger",
    "Village Rites",
    "Village Watch",
    "Villagers of Estwald",
    "Vindicate",
    "Vinelasher Kudzu",
    "Violent Outburst",
    "Viridian Emissary",
    "Virtue of Loyalty",
    "Virulent Sliver",
    "Visionary's Dance",
    "Visions of Beyond",
    "Vizier of Remedies",
    "Vodalian Arcanist",
    "Vodalian Hexcatcher",
    "Vodalian Soldiers",
    "Voice of Victory",
    "Voice of the Blessed",
    "Voice of the Woods",
    "Volcanic Fallout",
    "Volcanic Hammer",
    "Voldaren Epicure",
    "Volt Charge",
    "Voltaic Key",
    "Voracious Hydra",
    "Voracious Varmint",
    "Vorinclex, Voice of Hunger",
    "Vorstclaw",
    "Vryn Wingmare",
    "Vulshok Morningstar",
    "Walk the Plank",
    "Walking Ballista",
    "Walking Corpse",
    "Wall of Air",
    "Wall of Blood",
    "Wall of Blossoms",
    "Wall of Fire",
    "Wall of Frost",
    "Wall of Omens",
    "Wall of Roots",
    "Wall of Stone",
    "Wall of Swords",
    "Wall of Wood",
    "War Falcon",
    "Ward Sliver",
    "Warleader's Call",
    "Warren Instigator",
    "Wasteland",
    "Wasteland Viper",
    "Wastewood Verge",
    "Watcher Sliver",
    "Watchwolf",
    "Waterlogged Grove",
    "Wavebreak Hippocamp",
    "Wax // Wane",
    "Wayfarer's Bauble",
    "Weakness",
    "Weaponcraft Enthusiast",
    "Wear // Tear",
    "Wee Dragonauts",
    "Welcome to Sweettooth",
    "Welding Jar",
    "Welkin Tern",
    "Werebear",
    "Werewolf Pack Leader",
    "Whispering Madness",
    "Whispersilk Cloak",
    "White Knight",
    "White Orchid Phantom",
    "White Sun's Zenith",
    "Whitemane Lion",
    "Wickerbough Elder",
    "Wight of Precinct Six",
    "Wight of the Reliquary",
    "Wild Guess",
    "Wild Mongrel",
    "Wild Nacatl",
    "Wild Slash",
    "Wilderness Reclamation",
    "Wildgrowth Walker",
    "Wilt-Leaf Liege",
    "Wind Drake",
    "Wind Spirit",
    "Windborn Muse",
    "Windbrisk Heights",
    "Windswept Heath",
    "Wing Snare",
    "Wingcrafter",
    "Winged Sliver",
    "Wingmate Roc",
    "Wirewood Guardian",
    "Wisdom of Ages",
    "Wishclaw Talisman",
    "Witherbloom Charm",
    "Withered Wretch",
    "Wizened Cenn",
    "Wolfbriar Elemental",
    "Wolfir Silverheart",
    "Wood Elves",
    "Wooded Foothills",
    "Worldly Tutor",
    "Wrap in Vigor",
    "Wrath of God",
    "Wrench Mind",
    "Wrenn and Six",
    "Wring Flesh",
    "Writhing Chrysalis",
    "Yavimaya Elder",
    "Yavimaya, Cradle of Growth",
    "Yawgmoth, Thran Physician",
    "Yotian Soldier",
    "Young Pyromancer",
    "Young Wolf",
    "Youthful Knight",
    "Zealous Conscripts",
    "Zealous Persecution",
    "Zenith Flare",
    "Zhur-Taa Goblin",
    "Zhur-Taa Swine",
    "Zirda, the Dawnwaker",
    "Zo-Zu the Punisher",
    "Zombify",
    "Zopandrel, Hunger Dominus",
    "Zulaport Cutthroat",
    "Zuran Orb",
];

/// The vocabulary size at which indices were frozen — the 163 seed names
/// (2026-08-24, through "Zimone's Experiment") plus the reserved unknown
/// slot at 0.
///
/// **A literal, deliberately not `VOCAB_SNAPSHOT.len() + 1`.** The
/// snapshot grows by appending — the modern cube pool landed 2026-08-30 —
/// and a floor derived from the array's length would jump with every
/// append and refuse every net trained since the freeze as "pre-freeze",
/// `nets/champion.safetensors` (164 rows) first among them. The floor
/// marks the freeze *date*, not the current size: everything after
/// position 162 only ever grew the table's tail, which is exactly the
/// part padding recovers.
///
/// **A net trained at any size *below* this floor predates the freeze and
/// cannot be padded**, only retrained. Its indices came from the sorted
/// pool of its own day, and eleven cards were inserted mid-order before
/// this snapshot was taken, so nothing can say which card each of its
/// rows meant. Padding one would load cleanly and mean the wrong cards,
/// which is strictly worse than the loud failure it replaced. See
/// [`vocab_fit`].
pub const FROZEN_VOCAB_SIZE: usize = 164;

// The floor can never exceed the table it is a boundary into.
const _: () = assert!(FROZEN_VOCAB_SIZE <= VOCAB_SNAPSHOT.len() + 1);

/// Whether a net trained with `have` embedding rows can be fitted to a
/// current vocabulary of `want`.
///
/// * `have == want` — nothing to do.
/// * `FROZEN_VOCAB_SIZE <= have < want` — pad. Frozen indices mean every
///   row the net has still names the card it was trained on, and the cards
///   it never saw embed as zeros, which is what index 0 does for an off-set
///   card anyway.
/// * `have < FROZEN_VOCAB_SIZE` — refuse; see [`FROZEN_VOCAB_SIZE`].
/// * `have > want` — refuse. The encoder has no index to give the extra
///   rows, so the net saw cards this build does not have.
pub fn vocab_fit(have: usize, want: usize) -> Result<(), String> {
    if have > want {
        return Err(format!(
            "net vocab {have} is larger than the encoder's {want}: it was trained against a \
             card set this build does not have, so its indices mean different cards"
        ));
    }
    if have < FROZEN_VOCAB_SIZE && have != want {
        return Err(format!(
            "net vocab {have} predates the frozen index assignment ({FROZEN_VOCAB_SIZE}). Its \
             rows were indexed by the sorted card pool of its day, so there is no way to line \
             them up with the current one — this checkpoint needs retraining, it is not \
             corrupt. Nets trained at {FROZEN_VOCAB_SIZE} or above survive a card addition."
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_pre_freeze_net_is_refused_and_a_post_freeze_one_is_padded() {
        // The seven committed deck nets are 153 against a frozen floor of
        // 164 — the defect this module exists to close, and padding them
        // would be a silent wrong answer rather than a loud failure.
        assert!(vocab_fit(153, FROZEN_VOCAB_SIZE).is_err());
        assert!(vocab_fit(FROZEN_VOCAB_SIZE, FROZEN_VOCAB_SIZE + 8).is_ok());
        assert!(vocab_fit(FROZEN_VOCAB_SIZE + 8, FROZEN_VOCAB_SIZE).is_err());
        // An exact match always passes, whatever the size — that is how a
        // net older than the freeze still works on the build it was trained
        // against.
        assert!(vocab_fit(153, 153).is_ok());
        assert!(vocab_fit(FROZEN_VOCAB_SIZE, FROZEN_VOCAB_SIZE).is_ok());
    }
}
