#!/usr/bin/env python3
"""Regenerate `CR_COVERAGE.md` — which Comprehensive Rules sections have
conformance tests.

Scans every `#[test] fn cr_<section>[_<sub>]_<slug>` in
`crabomination_tests/tests/`, maps it back to the rule number it names, and
cross-references the rule titles in the shipped rules text. Sections with no
test are listed as gaps so the roadmap's conformance row is measurable.

    python3 scripts/cr_coverage.py
"""

import re
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TESTS = REPO / "crabomination_tests" / "tests"
RULES = REPO / "crabomination" / "MagicCompRules_20260417.txt"
OUT = REPO / "CR_COVERAGE.md"

# `cr_509_1b_multi_block` → section 509, subrule 1b. A bare `cr_509_...` with
# no numeric second group is a whole-section test.
TEST_RE = re.compile(r"fn (cr_(\d{3})(?:_(\d+[a-z]?))?_[a-z0-9_]+)\s*\(")
# "509.1b. A creature can block only..." — the rules text's numbering.
RULE_RE = re.compile(r"^(\d{3})\.(\d+[a-z]?)?\.?\s+(.*)$")


def rule_titles() -> dict[str, str]:
    """Section number → the section's opening sentence."""
    titles: dict[str, str] = {}
    if not RULES.exists():
        return titles
    for line in RULES.read_text(encoding="utf-8", errors="replace").splitlines():
        m = RULE_RE.match(line.strip())
        if not m:
            continue
        section, sub, text = m.groups()
        if sub is None and section not in titles:
            titles[section] = text.strip()
    return titles


def main() -> None:
    by_section: dict[str, set[str]] = defaultdict(set)
    subrules: dict[str, set[str]] = defaultdict(set)
    for path in sorted(TESTS.rglob("*.rs")):
        src = path.read_text(encoding="utf-8", errors="replace")
        rel = path.relative_to(REPO)
        for name, section, sub in TEST_RE.findall(src):
            by_section[section].add(f"{rel}::{name}")
            if sub:
                subrules[section].add(sub)

    titles = rule_titles()
    tested = sorted(by_section)
    total_tests = sum(len(v) for v in by_section.values())

    lines = [
        "# CR conformance coverage",
        "",
        "Generated by `scripts/cr_coverage.py` — do not hand-edit.",
        "",
        f"**{len(tested)} Comprehensive Rules sections** carry at least one",
        f"conformance test ({total_tests} tests total). A section counts as",
        "covered when a test is named `cr_<section>[_<subrule>]_<slug>`.",
        "",
        "| Section | Title | Subrules tested | Tests |",
        "| --- | --- | --- | --- |",
    ]
    for section in tested:
        title = titles.get(section, "")
        if len(title) > 70:
            title = title[:67] + "…"
        subs = ", ".join(sorted(subrules[section])) or "—"
        lines.append(f"| {section} | {title} | {subs} | {len(by_section[section])} |")

    # Gaps: numbered sections in the rules text with no test at all.
    gaps = [s for s in sorted(titles) if s not in by_section]
    lines += [
        "",
        "## Untested sections",
        "",
        f"{len(gaps)} numbered sections have no `cr_<section>_` test:",
        "",
    ]
    lines.append(", ".join(gaps) if gaps else "_none_")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} — {len(tested)} sections covered, {len(gaps)} gaps.")


if __name__ == "__main__":
    main()
