#!/usr/bin/env python3
"""Regenerate `crabomination/src/catalog/sets/stx/all_factories.rs`.

The STX catalog has 2500+ public card factories spread across
~10 files (silverquill / witherbloom / lorehold / quandrix / prismari /
mono / iconic / legends / extras / lessons / shared). The
`all_known_factories` snapshot-reload path needs to know about every
one of them so a mid-game save involving STX permanents round-trips
through the `name → factory` index.

Rather than rebuild this with a `build.rs` (which would slow every
fresh build), this script lazily generates the list and commits the
output to the tree. Run it whenever you add new `pub fn name() ->
CardDefinition` entries to one of the STX files.

Usage:
    python3 scripts/gen_stx_factory_list.py

Idempotent: rewrites the file in place. The diff is just the new
factory lines.
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
STX_DIR = REPO / "crabomination" / "src" / "catalog" / "sets" / "stx"
OUT = STX_DIR / "all_factories.rs"

FILES = ['silverquill', 'witherbloom', 'lorehold', 'quandrix', 'prismari',
         'mono', 'iconic', 'legends', 'extras', 'lessons', 'shared']

FN_RE = re.compile(r'^pub fn ([a-z_][a-z0-9_]*)\(\) -> CardDefinition\b', re.MULTILINE)

def main():
    out_lines = [
        "//! Aggregate factory list for the STX (Strixhaven base set) catalog.",
        "//!",
        "//! Auto-generated by `scripts/gen_stx_factory_list.py` (committed as",
        "//! a snapshot for snapshot-reload + audit-picker discovery, NOT",
        "//! regenerated on every build — the catalog is large so we keep the",
        "//! list source-controlled rather than rebuilt with a build script).",
        "//!",
        "//! Used by `crabomination::catalog::all_known_factories` to populate",
        "//! the snapshot-load `name → factory` index with STX cards, so",
        "//! mid-game saves involving STX permanents round-trip cleanly.",
        "",
        "use crate::card::CardDefinition;",
        "",
        "type Factory = fn() -> CardDefinition;",
        "",
        "/// Every STX card factory currently exposed under",
        "/// `crate::catalog::sets::stx::*`. Includes both real Strixhaven 2021",
        "/// printed cards and the synthesised batch-suffixed variants. Walking",
        "/// the slice is cheap; `all_known_factories` dedupes by function-",
        "/// pointer so the cost is bounded.",
        "pub fn all_stx_card_factories() -> &'static [Factory] {",
        "    &[",
    ]
    total = 0
    for f in FILES:
        path = STX_DIR / f"{f}.rs"
        if not path.exists():
            continue
        content = path.read_text(encoding='utf-8')
        fns = FN_RE.findall(content)
        if fns:
            out_lines.append(f"        // ── {f} ({len(fns)} factories) ──")
            for fn in fns:
                out_lines.append(f"        super::{f}::{fn},")
            total += len(fns)
    out_lines.append("    ]")
    out_lines.append("}")
    out_lines.append("")
    OUT.write_text('\n'.join(out_lines), encoding='utf-8')
    print(f"Wrote {OUT} with {total} factories.")


if __name__ == "__main__":
    main()
