#!/usr/bin/env python3
"""Regenerate `crabomination_catalog/src/sets/all_factories.rs`.

Walks every set module under `crabomination_catalog/src/sets/` and emits a
single aggregate slice of every zero-arg `pub fn name() -> CardDefinition`
factory, qualified through each set's public re-export path. The
`all_known_factories` snapshot-reload registry extends from this list, so a
card defined anywhere in the catalog is reachable by name without a
hand-maintained per-set list (the drift that left ~500 cards unregistered).

Run after adding new card factories:
    python3 scripts/gen_factory_lists.py

Idempotent: rewrites the file in place.

Covers `sets::stx` too (superseding `scripts/gen_stx_factory_list.py`,
which predates the catalog crate move); the registry dedupes by function
pointer so the legacy `all_stx_card_factories` list coexisting is harmless.
"""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SETS = REPO / "crabomination_catalog" / "src" / "sets"
OUT = SETS / "all_factories.rs"

EXCLUDE = {"all_factories"}

FN_RE = re.compile(
    r"^pub fn ([a-z_][a-z0-9_]*)\(\) -> CardDefinition\b", re.MULTILINE
)


def factories_in(path: Path) -> list[str]:
    return FN_RE.findall(path.read_text(encoding="utf-8"))


def main() -> None:
    out = [
        "//! Aggregate factory list for the whole catalog crate.",
        "//!",
        "//! Auto-generated by `scripts/gen_factory_lists.py`; committed as a",
        "//! snapshot rather than rebuilt by a build script. Regenerate after",
        "//! adding card factories.",
        "//!",
        "//! `crabomination::catalog::all_known_factories` extends from this so",
        "//! every defined card resolves through the snapshot/decklist",
        "//! `name -> factory` index.",
        "",
        "use crate::card::CardDefinition;",
        "",
        "type Factory = fn() -> CardDefinition;",
        "",
        "/// Every zero-arg card factory exposed under `sets::*`.",
        "pub fn all_catalog_card_factories() -> &'static [Factory] {",
        "    &[",
    ]
    total = 0
    # Directory modules (re-export their files via `pub use file::*`) and
    # single-file modules (lci.rs, mkm.rs, xtra.rs, ...).
    entries = sorted(SETS.iterdir(), key=lambda p: p.name)
    for entry in entries:
        name = entry.name.removesuffix(".rs")
        if name in EXCLUDE or name == "mod":
            continue
        if entry.is_dir():
            fns: list[str] = []
            for f in sorted(entry.glob("*.rs")):
                if f.stem == "mod":
                    continue
                fns.extend(factories_in(f))
            # Plus factories defined directly in the dir's mod.rs.
            mod_rs = entry / "mod.rs"
            if mod_rs.exists():
                fns.extend(factories_in(mod_rs))
        elif entry.suffix == ".rs":
            fns = factories_in(entry)
        else:
            continue
        if not fns:
            continue
        out.append(f"        // -- {name} ({len(fns)} factories) --")
        for fn in fns:
            out.append(f"        super::{name}::{fn},")
        total += len(fns)
    out += ["    ]", "}", ""]
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {OUT} with {total} factories.")


if __name__ == "__main__":
    main()
