#!/bin/bash
# pod_power.sh BIN [GAMES] [SHUFFLES] [SEED0] — measure every target deck's
# win share in six-seat pods of the default pilot and write
# crabomination/src/pod/power_table.rs, the table behind the deck picker's
# power tiers (`pod::power`).
#
# Each shuffle deals the decks 1..N (N read off `bot_ladder`) into groups of
# six (the last topped up at random) and plays GAMES games a group, seat
# rotation inside `bot_ladder` so seat order cancels. A deck's share is its
# wins over its games; six seats because that is where the spread is widest
# (the same decks run 1-67 %), and every deck meets many opponents.
#
#   cargo build --profile release-fast -p crabomination --bin bot_ladder
#   scripts/pod_power.sh target/release-fast/bot_ladder 120 4 9500
#
# ~15-20 minutes on 24 cores at the defaults. Re-run when the bot or the
# pool moves enough to matter; a deck added since the last run is shown as
# unrated and dealt as a middle-tier deck.
set -e
BIN=$1; GAMES=${2:-120}; SHUF=${3:-4}; SEED0=${4:-9500}
ND=$("$BIN" --commander --pod-decks 999 --games 1 2>&1 | grep -o '1\.\.=[0-9]*' | cut -d= -f2)
[ -n "$ND" ] || { echo "cannot read the deck count from $BIN" >&2; exit 1; }
OUT=$(mktemp)
for rep in $(seq 0 $((SHUF - 1))); do
  seed=$((SEED0 + rep * 100))
  for g in $(python3 - "$ND" "$((SEED0 + rep))" <<'PY'
import random, sys
nd, s = int(sys.argv[1]), int(sys.argv[2])
r = random.Random(s); ix = list(range(1, nd + 1)); r.shuffle(ix)
while len(ix) % 6: ix.append(r.randint(1, nd))
for i in range(0, len(ix), 6): print(",".join(map(str, ix[i:i + 6])))
PY
  ); do
    timeout 600 "$BIN" --commander --seats 6 --a dflt --pod-decks "$g" --games "$GAMES" --seed "$seed" \
      | grep -E '^  deck [0-9]' | sed "s/^/$GAMES /" >> "$OUT" || echo "group $g seed $seed failed" >&2
    seed=$((seed + 1))
  done
done
python3 - "$OUT" "$GAMES" "$SHUF" "$SEED0" "$ND" > crabomination/src/pod/power_table.rs <<'PY'
import re, sys, collections, datetime, json
path, games, shuf, seed0, nd = sys.argv[1:6]
w = collections.Counter(); g = collections.Counter()
for line in open(path):
    m = re.match(r'(\d+)\s+deck \d+\s+(.*?)\s+wins\s+(\d+)', line)
    if m:
        g[m.group(2)] += int(m.group(1)); w[m.group(2)] += int(m.group(3))
rows = sorted(g, key=lambda k: -w[k] / g[k])
print("// GENERATED by scripts/pod_power.sh — do not edit by hand; re-run it.")
print(f"//! Each target deck's win share in six-seat pods of the default pilot,")
print(f"//! per mille: {shuf} shuffles of the {nd} decks into groups of six,")
print(f"//! {games} games a group, seeds {seed0}+ ({datetime.date.today()}).")
print("")
print("/// (deck name, wins per thousand games, games played).")
print("pub(super) const MEASURED: &[(&str, u16, u32)] = &[")
for k in rows:
    print(f'    ({json.dumps(k, ensure_ascii=False)}, {round(1000 * w[k] / g[k])}, {g[k]}),')
print("];")
PY
rm -f "$OUT"
echo "wrote crabomination/src/pod/power_table.rs ($(grep -c '^    ("' crabomination/src/pod/power_table.rs) decks)"
