//! Deck power tiers, for dealing balanced pods: each target deck's measured
//! win share in six-seat pods of the default bot (`power_table`, generated by
//! `scripts/pod_power.sh`), bucketed against the one game in six a deck is
//! due. The same bot plays every seat, so a tier says how a list does against
//! the field under bot play — not what it is worth in a human's hands. At the
//! first measurement the same 183 decks ran from 0 % to 67 % (Gisela, the
//! Broken Blade), so a pod dealt at random could seat a deck that wins two
//! games in three against three that almost never do.

/// Tiers run 1 (weakest) ..= `TIERS` (strongest).
pub const TIERS: u8 = 5;

/// The middle tier: decks that win about their share (0.75-1.25x).
pub const MIDDLE: u8 = 3;

/// The tier a deck the table predates is dealt as: the middle.
pub const UNRATED: u8 = MIDDLE;

/// `name`'s measured six-seat win share, wins per thousand games — `None`
/// for a deck added since the table was generated.
pub fn measured_share(name: &str) -> Option<u16> {
    super::power_table::MEASURED.iter().find(|(n, ..)| *n == name).map(|&(_, share, _)| share)
}

/// `name`'s power tier, 1 (weakest) ..= [`TIERS`] (strongest), or `None`
/// for a deck the table predates.
pub fn tier(name: &str) -> Option<u8> {
    measured_share(name).map(tier_of_share)
}

/// A six-seat win share (per mille) against the 1 in 6 a deck is due:
/// under 0.4x, 0.4-0.75x, 0.75-1.25x, 1.25-2x, 2x and over. Fixed ratios
/// rather than quantiles, so a tier keeps its meaning when the table is
/// regenerated; at the first measurement they held 41 / 33 / 57 / 37 / 15
/// decks.
pub fn tier_of_share(per_mille: u16) -> u8 {
    // share / (1/6) in percent = per_mille * 6 / 10
    match u32::from(per_mille) * 6 / 10 {
        0..40 => 1,
        40..75 => 2,
        75..125 => 3,
        125..200 => 4,
        _ => 5,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The table names only decks that exist, once each: a renamed or
    /// dropped deck would silently lose its tier. (A deck ADDED since the
    /// table was generated is fine — it deals as `UNRATED` until the next
    /// `scripts/pod_power.sh`.)
    #[test]
    fn the_power_table_names_real_decks_once() {
        let decks: Vec<&str> = crate::pod::target_decks().iter().map(|d| d.name).collect();
        let mut seen = std::collections::HashSet::new();
        for (name, share, games) in super::super::power_table::MEASURED {
            assert!(decks.contains(name), "{name} is not a target deck");
            assert!(seen.insert(*name), "{name} is listed twice");
            assert!(*share <= 1000 && *games > 0, "{name}: {share} / {games}");
        }
    }

    #[test]
    fn tiers_bucket_the_share_against_one_in_six() {
        // 1/6 is 166.7 per mille: the middle tier straddles it.
        assert_eq!(tier_of_share(0), 1);
        assert_eq!(tier_of_share(66), 1);
        assert_eq!(tier_of_share(67), 2);
        assert_eq!(tier_of_share(125), 3);
        assert_eq!(tier_of_share(167), 3);
        assert_eq!(tier_of_share(209), 4);
        assert_eq!(tier_of_share(334), 5);
        assert_eq!(tier_of_share(1000), 5);
    }
}
